/*** Autogenerated by WIDL 9.18 from dlls/vbscript/vbscript_classes.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __vbscript_classes_h__
#define __vbscript_classes_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __VBScriptRegExp_FWD_DEFINED__
#define __VBScriptRegExp_FWD_DEFINED__
#ifdef __cplusplus
typedef class VBScriptRegExp VBScriptRegExp;
#else
typedef struct VBScriptRegExp VBScriptRegExp;
#endif /* defined __cplusplus */
#endif /* defined __VBScriptRegExp_FWD_DEFINED__ */

#ifndef __VBScript_FWD_DEFINED__
#define __VBScript_FWD_DEFINED__
#ifdef __cplusplus
typedef class VBScript VBScript;
#else
typedef struct VBScript VBScript;
#endif /* defined __cplusplus */
#endif /* defined __VBScript_FWD_DEFINED__ */

#ifndef __VBScriptAuthor_FWD_DEFINED__
#define __VBScriptAuthor_FWD_DEFINED__
#ifdef __cplusplus
typedef class VBScriptAuthor VBScriptAuthor;
#else
typedef struct VBScriptAuthor VBScriptAuthor;
#endif /* defined __cplusplus */
#endif /* defined __VBScriptAuthor_FWD_DEFINED__ */

#ifndef __VBScriptEncode_FWD_DEFINED__
#define __VBScriptEncode_FWD_DEFINED__
#ifdef __cplusplus
typedef class VBScriptEncode VBScriptEncode;
#else
typedef struct VBScriptEncode VBScriptEncode;
#endif /* defined __cplusplus */
#endif /* defined __VBScriptEncode_FWD_DEFINED__ */

/* Headers for imported files */


#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * VBScriptRegExp coclass
 */

DEFINE_GUID(CLSID_VBScriptRegExp, 0x3f4daca4, 0x160d, 0x11d2, 0xa8,0xe9, 0x00,0x10,0x4b,0x36,0x5c,0x9f);

#ifdef __cplusplus
class DECLSPEC_UUID("3f4daca4-160d-11d2-a8e9-00104b365c9f") VBScriptRegExp;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(VBScriptRegExp, 0x3f4daca4, 0x160d, 0x11d2, 0xa8,0xe9, 0x00,0x10,0x4b,0x36,0x5c,0x9f)
#endif
#endif

/*****************************************************************************
 * VBScript coclass
 */

DEFINE_GUID(CLSID_VBScript, 0xb54f3741, 0x5b07, 0x11cf, 0xa4,0xb0, 0x00,0xaa,0x00,0x4a,0x55,0xe8);

#ifdef __cplusplus
class DECLSPEC_UUID("b54f3741-5b07-11cf-a4b0-00aa004a55e8") VBScript;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(VBScript, 0xb54f3741, 0x5b07, 0x11cf, 0xa4,0xb0, 0x00,0xaa,0x00,0x4a,0x55,0xe8)
#endif
#endif

/*****************************************************************************
 * VBScriptAuthor coclass
 */

DEFINE_GUID(CLSID_VBScriptAuthor, 0xb54f3742, 0x5b07, 0x11cf, 0xa4,0xb0, 0x00,0xaa,0x00,0x4a,0x55,0xe8);

#ifdef __cplusplus
class DECLSPEC_UUID("b54f3742-5b07-11cf-a4b0-00aa004a55e8") VBScriptAuthor;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(VBScriptAuthor, 0xb54f3742, 0x5b07, 0x11cf, 0xa4,0xb0, 0x00,0xaa,0x00,0x4a,0x55,0xe8)
#endif
#endif

/*****************************************************************************
 * VBScriptEncode coclass
 */

DEFINE_GUID(CLSID_VBScriptEncode, 0xb54f3743, 0x5b07, 0x11cf, 0xa4,0xb0, 0x00,0xaa,0x00,0x4a,0x55,0xe8);

#ifdef __cplusplus
class DECLSPEC_UUID("b54f3743-5b07-11cf-a4b0-00aa004a55e8") VBScriptEncode;
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(VBScriptEncode, 0xb54f3743, 0x5b07, 0x11cf, 0xa4,0xb0, 0x00,0xaa,0x00,0x4a,0x55,0xe8)
#endif
#endif

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __vbscript_classes_h__ */
