//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VBATest.rc
//
#define IDC_COLOR                       15
#define IDS_PROJNAME                    100
#define IDR_VBATest                     100
#define IDR_SURFACE                     101
#define IDS_TB_TIMER                    101
#define IDS_DRAGPOINT_DESC              102
#define IDR_DragPoint                   103
#define IDS_TB_SELECT                   103
#define IDS_TB_WALL                     104
#define IDC_POINTER                     104
#define IDS_TB_FLIPPER                  105
#define IDS_TB_PLAY                     106
#define IDS_FLIPPER_DESC                107
#define IDR_Flipper                     108
#define IDC_SELECT                      109
#define IDC_WALL                        110
#define IDC_CUR_LIGHT                   110
#define IDC_FLIPPER                     111
#define IDS_TIMER_DESC                  112
#define IDR_Timer                       113
#define IDC_TIMER                       114
#define IDS_PLUNGER_DESC                115
#define IDR_Plunger                     116
#define IDS_TB_PLUNGER                  116
#define IDC_PLUNGER                     117
#define IDS_TEXTBOX_DESC                118
#define IDR_Textbox                     119
#define IDS_TB_TEXTBOX                  119
#define IDC_TEXTBOX                     120
#define IDS_BUMPER_DESC                 121
#define IDR_Bumper                      122
#define IDS_TB_BUMPER                   122
#define IDC_BUMPER                      123
#define IDS_PIEVENTHANDLER_DESC         124
#define IDR_PIEventHandler              125
#define IDS_TRIGGER_DESC                126
#define IDR_Trigger                     127
#define IDS_TB_TRIGGER                  127
#define IDC_TRIGGER                     128
#define IDS_LIGHT_DESC                  129
#define IDR_Light                       130
#define IDS_TB_LIGHT                    130
#define IDC_LIGHT                       131
#define IDS_KICKER_DESC                 132
#define IDR_Kicker                      133
#define IDS_TB_KICKER                   133
#define IDC_KICKER                      134
#define IDS_TB_TARGET                   134
#define IDC_TARGET                      135
#define IDS_TB_DECAL                    135
#define IDC_DECAL                       136
#define IDS_TB_PROPERTIES               136
#define IDC_MAGNIFY                     137
#define IDS_TB_MAGNIFY                  137
#define IDC_CUR_MAGNIFY                 137
#define IDS_GATE_DESC                   138
#define IDC_CUR_WALL                    138
#define IDR_Gate                        139
#define IDS_TB_GATE                     139
#define IDC_CUR_FLIPPER                 139
#define IDC_GATE                        140
#define IDC_CUR_TRIGGER                 140
#define IDS_SPINNER_DESC                141
#define IDC_CUR_GATE                    141
#define IDR_Spinner                     142
#define IDS_TB_SPINNER                  142
#define IDC_CUR_TIMER                   142
#define IDC_SPINNER                     143
#define IDC_CUR_PLUNGER                 143
#define IDS_RAMP_DESC                   144
#define IDC_CUR_TEXTBOX                 144
#define IDR_Ramp                        145
#define IDS_TB_RAMP                     145
#define IDC_CUR_BUMPER                  145
#define IDC_RAMP                        146
#define IDS_TB_SCRIPT                   146
#define IDC_CUR_KICKER                  146
#define ID_DRAWINFRONT                  147
#define IDC_CUR_TARGET                  147
#define IDS_SAVE_CHANGES                147
#define ID_DRAWINBACK                   148
#define IDC_CUR_DECAL                   148
#define IDS_NAME                        148
#define IDC_CUR_SPINNER                 149
#define IDS_IMPORTPATH                  149
#define IDC_CUR_RAMP                    150
#define IDS_REPLACESOUND                150
#define IDS_REMOVESOUND                 151
#define IDS_IMAGE_PREVIEW               152
#define IDS_REMOVEIMAGE                 153
#define IDS_REPLACEIMAGE                154
#define IDS_TABLE                       155
#define IDS_SCRIPT                      156
#define IDS_SAVE_CHANGES1               157
#define IDS_SAVE_CHANGES2               158
#define IDS_DRAWINFRONT                 159
#define IDS_DRAWINBACK                  160
#define IDS_SAVEERROR                   161
#define IDR_APPMENU                     201
#define IDC_SOUNDLIST                   201
#define IDR_POINTMENU                   202
#define IDC_IMPORT                      203
#define IDC_REIMPORT                    204
#define IDB_TB_SELECT                   205
#define IDC_REIMPORTFROM                205
#define IDC_PLAY                        206
#define IDC_DELETE                      207
#define IDB_ICON_TRIGGER                208
#define IDC_RENAME                      208
#define IDC_PICTUREPREVIEW              209
#define IDC_ROTATEBY                    210
#define IDC_CENTERX                     211
#define IDC_CENTERY                     212
#define IDB_ICON_TIMER                  213
#define IDB_ICON_FLIPPER                214
#define IDC_SCALEFACTOR                 214
#define IDB_ICON_LIGHT                  215
#define IDR_VPACCEL                     216
#define IDC_PROGRESS2                   216
#define IDC_SCALEY                      216
#define IDD_SOUNDDIALOG                 217
#define IDD_IMAGEDIALOG                 218
#define IDI_APPICON                     218
#define IDC_STEP                        218
#define IDC_STATUSNAME                  218
#define IDB_SUNBURST                    219
#define IDB_BALLTEXTURE                 220
#define IDR_SURFACEMENU                 221
#define IDD_ROTATE                      222
#define IDR_MULTIMENU                   222
#define IDD_SCALE                       223
#define IDB_WHITE                       227
#define IDD_PROGRESS                    228
#define IDD_PROPTABLE                   229
#define IDD_PROPLIGHT                   231
#define IDD_PROPRAMP                    232
#define IDD_PROPTIMER                   233
#define IDD_PROPFLIPPER                 234
#define IDD_PROPPLUNGER                 235
#define IDD_PROPTEXTBOX                 236
#define IDD_PROPBUMPER                  237
#define IDD_PROPTRIGGER                 238
#define IDD_PROPKICKER                  239
#define IDD_PROPDECAL                   240
#define IDD_PROPGATE                    241
#define IDD_PROPSPINNER                 242
#define IDD_PROPPOINT                   243
#define IDD_PROPWALL                    244
#define IDD_CODEVIEW                    245
#define ID_FIND                         245
#define ID_COMPILE                      246
#define IDD_ABOUT                       250
#define IDC_WEBSITE                     250
#define IDC_TRANSSITE                   251
#define IDI_SCRIPTICON                  252
#define IDC_WINDOW                      255
#define IDD_VIDEO_OPTIONS               255
#define IDC_FULLSCREEN                  256
#define IDD_FONTDIALOG                  256
#define IDC_SIZELIST                    257
#define IDB_SUNBURST3                   260
#define IDD_KEYS                        261
#define IDC_LEFTFLIPPERBUTTON           262
#define IDD_TRANSLATE                   262
#define IDC_RIGHTFLIPPERBUTTON          264
#define IDB_LOGO                        264
#define IDR_TABLE_NEW                   265
#define IDC_LEFTTILTBUTTON              266
#define IDI_TABLEICON                   266
#define IDR_SCRIPTMENU                  267
#define IDC_RIGHTTILTBUTTON             268
#define IDD_AUDIO_OPTIONS               268
#define IDC_PLUNGERBUTTON               269
#define IDD_GAMEPAUSE                   269
#define IDC_CENTERTILTBUTTON            270
#define IDR_CODEVIEWACCEL               271
#define IDC_LEFTFLIPPER                 273
#define IDC_RIGHTFLIPPER                274
#define IDC_LEFTTILT                    275
#define IDC_RIGHTTILT                   276
#define IDC_CENTERTILT                  277
#define IDC_BUTTON1                     280
#define IDC_ITEMLIST                    281
#define IDC_EVENTLIST                   282
#define IDC_OFFSETX                     282
#define IDC_OFFSETY                     283
#define IDC_PLAY_MUSIC                  285
#define IDC_MUSIC_SLIDER                286
#define IDC_PLAY_SOUND                  287
#define IDC_SQUARE                      287
#define IDC_SOUND_SLIDER                288
#define IDC_STATIC_MUSIC                289
#define IDC_STATIC_SOUND                290
#define IDC_STATIC_SCALEY               291
#define ID_QUIT                         293
#define ID_RESUME                       294
#define IDC_CHECKBLIT                   295
#define IDM_NEW                         32768
#define IDM_OPEN                        32769
#define IDM_CLOSE                       32770
#define IDM_SAVE                        32771
#define IDM_SAVEAS                      32772
#define ID_SCRIPT_SHOWIDE               32773
#define ID_ADDPOINT                     32775
#define ID_POINTMENU_SMOOTH             32776
#define ID_WINDOW_TILE                  32783
#define ID_WINDOW_CASCADE               32784
#define ID_WINDOW_ARRANGEICONS          32785
#define ID_TABLE_PLAY                   32786
#define IDC_COPY                        32787
#define IDC_PASTE                       32788
#define ID_FILE_EXPORT_BLUEPRINT        32790
#define ID_TABLE_SOUNDMANAGER           32792
#define ID_TABLE_IMAGEMANAGER           32793
#define ID_EDIT_UNDO                    32794
#define ID_EDIT_PROPERTIES              32795
#define ID_POINTMENU_SLINGSHOT          32796
#define ID_WALLMENU_FLIP                32797
#define ID_WALLMENU_MIRROR              32798
#define ID_WALLMENU_ROTATE              32799
#define ID_WALLMENU_SCALE               32800
#define ID_WALLMENU_ADDPOINT            32801
#define ID_HELP_ABOUT                   32802
#define ID_EDIT_SCRIPT                  32803
#define ID_EDIT_VIDEOOPTIONS            32804
#define ID_TABLE_FONTMANAGER            32805
#define ID_EDIT_KEYS                    32806
#define ID_WALLMENU_TRANSLATE           32807
#define ID_EDIT_COPY                    32811
#define ID_EDIT_CUT                     32813
#define ID_EDIT_PASTE                   32814
#define ID_EDIT_AUDIOOPTIONS            32815

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        272
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         297
#define _APS_NEXT_SYMED_VALUE           149
#endif
#endif
