//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vpinball_eng.rc
//
#define DISPID_Textbox_BackColor        1
#define DISPID_Textbox_FontColor        2
#define DISPID_Light_State              2
#define DISPID_Gate_Length              3
#define DISPID_Spinner_Length           3
#define DISPID_DispReel_FontColor2      3
#define IDC_ADD                         3
#define DISPID_SIZE_Z                   3
#define DISPID_Gate_Rotation            4
#define DISPID_Textbox_Font             4
#define DISPID_POSITION_Z               4
#define DISPID_SIZE_X                   5
#define DISPID_Surface_SideColor        6
#define DISPID_SIZE_Y                   6
#define DISPID_Surface_SideColor2       7
#define DISPID_POSITION_X               7
#define DISPID_Gate_Rotation3           8
#define DISPID_POSITION_Y               8
#define DISPID_Decal_SizingType         9
#define DISPID_Surface_FaceColor        10
#define DISPID_Light_BlinkInterval      10
#define DISPID_Light_BlinkInterval2     11
#define DISPID_Light_BlinkDuration      11
#define DISPID_Decal_Font               12
#define DISPID_ROTRA1                   12
#define IDC_DBG_LIGHT_INTENSITY         12
#define DISPID_ROTRA2                   13
#define DISPID_TOPCOLOR                 14
#define DISPID_ROTRA3                   14
#define IDC_COLOR                       15
#define DISPID_TOPVISIBLE               15
#define DISPID_ROTRA4                   15
#define DISPID_Flipper_Speed            16
#define DISPID_ROTRA5                   16
#define IDC_COLOR2                      16
#define DISPID_ROTRA6                   17
#define IDC_COLOR3                      17
#define DISPID_SIDECOLOR                18
#define IDC_COLOR4                      18
#define DISPID_SIDEVISIBLE              19
#define IDC_COLOR5                      19
#define DISPID_SMOOTHNORMALS            21
#define DISPID_ROTRA7                   21
#define DISPID_DRAWINSIDE               22
#define DISPID_ROTRA8                   22
#define DISPID_ROTRA9                   23
#define DISPID_HEIGHTOFFSET             24
#define IDC_ORIENTATION_EDIT            25
#define IDC_RINGSPEED_EDIT              26
#define IDS_PROJNAME                    100
#define IDR_VPINBALL                    100
#define IDR_SURFACE                     101
#define IDS_TB_TIMER                    101
#define IDD_CODEVIEW_PREFS              101
#define IDS_DRAGPOINT_DESC              102
#define IDR_DRAG_POINT                  103
#define IDS_TB_SELECT                   103
#define IDS_TB_WALL                     104
#define IDS_TB_FLIPPER                  105
#define IDS_TB_PLAY                     106
#define IDS_FLIPPER_DESC                107
#define IDC_TABLE_SCALEZ                108
#define IDR_FLIPPER                     108
#define IDS_LAYER1                      108
#define IDC_SELECT                      109
#define DISPID_Table_GridSize           109
#define IDS_ASSIGNTO                    109
#define ID_INSERT_WALL                  110
#define IDC_LIGHT                       110
#define IDS_LAYER2                      110
#define ID_INSERT_FLIPPER               111
#define IDS_LAYER3                      111
#define IDS                             111
#define IDS_TIMER_DESC                  112
#define IDR_TIMER                       113
#define IDS_LAYER4                      113
#define ID_INSERT_TIMER                 114
#define IDS_LAYER5                      114
#define IDS_PLUNGER_DESC                115
#define IDR_PLUNGER                     116
#define IDS_TB_PLUNGER                  116
#define ID_INSERT_PLUNGER               117
#define IDC_PLUNGER_TEXT                117
#define IDS_LAYER6                      117
#define IDS_TEXTBOX_DESC                118
#define IDC_STARTGAME                   118
#define IDR_TEXTBOX                     119
#define IDS_TB_TEXTBOX                  119
#define IDC_LMAGSAVE                    119
#define ID_INSERT_TEXTBOX               120
#define IDS_DISPREEL_DESC               120
#define IDC_RMAGSAVE                    120
#define IDS_BUMPER_DESC                 121
#define IDC_MECHTILT                    121
#define IDR_BUMPER                      122
#define IDS_TB_BUMPER                   122
#define IDC_STARTGAME2                  122
#define ID_INSERT_BUMPER                123
#define IDS_TB_DISPREEL                 123
#define IDS_PIEVENTHANDLER_DESC         124
#define IDR_PI_EVENT_HANDLER            125
#define IDS_LAYER7                      125
#define IDS_TRIGGER_DESC                126
#define IDR_TRIGGER                     127
#define IDS_TB_TRIGGER                  127
#define ID_INSERT_TRIGGER               128
#define IDS_STRING128                   128
#define IDS_LAYER8                      128
#define IDS_LIGHT_DESC                  129
#define IDR_LIGHT                       130
#define IDS_TB_LIGHT                    130
#define ID_INSERT_LIGHT                 131
#define IDS_DRAWING_ORDER_HIT           131
#define IDS_KICKER_DESC                 132
#define IDR_KICKER                      133
#define IDS_TB_KICKER                   133
#define ID_INSERT_KICKER                134
#define IDS_TB_TARGET                   134
#define ID_INSERT_TARGET                135
#define IDS_TB_DECAL                    135
#define ID_INSERT_DECAL                 136
#define IDS_TB_PROPERTIES               136
#define ID_TABLE_MAGNIFY                137
#define IDS_TB_MAGNIFY                  137
#define IDC_MAGNIFY                     137
#define IDS_GATE_DESC                   138
#define IDC_WALL                        138
#define IDR_GATE                        139
#define IDS_TB_GATE                     139
#define IDC_FLIPPER                     139
#define ID_INSERT_GATE                  140
#define IDC_TRIGGER                     140
#define IDS_WRONGFILEVERSION2           140
#define IDS_TB_FLASHER                  140
#define IDS_SPINNER_DESC                141
#define IDC_GATE                        141
#define IDR_SPINNER                     142
#define IDS_TB_SPINNER                  142
#define IDC_TIMER                       142
#define ID_INSERT_SPINNER               143
#define IDC_PLUNGER                     143
#define IDS_SELECT_COLLECTION           143
#define IDS_TO_COLLECTION               143
#define IDS_RAMP_DESC                   144
#define IDC_TEXTBOX                     144
#define IDR_RAMP                        145
#define IDS_TB_RAMP                     145
#define IDC_BUMPER                      145
#define ID_INSERT_RAMP                  146
#define IDS_TB_SCRIPT                   146
#define IDC_KICKER                      146
#define ID_DRAWINFRONT                  147
#define IDC_TARGET                      147
#define IDS_SAVE_CHANGES                147
#define IDS_TB_RUBBER                   147
#define ID_DRAWINBACK                   148
#define IDC_DECAL                       148
#define IDS_NAME                        148
#define ID_SETASDEFAULT                 149
#define IDC_SPINNER                     149
#define IDS_IMPORTPATH                  149
#define IDC_RAMP                        150
#define IDS_REPLACESOUND                150
#define IDS_REMOVESOUND                 151
#define IDS_IMAGE_PREVIEW               152
#define IDS_REMOVEIMAGE                 153
#define IDS_REPLACEIMAGE                154
#define IDS_TABLE                       155
#define IDS_SCRIPT                      156
#define IDS_SAVE_CHANGES1               157
#define IDS_SAVE_CHANGES2               158
#define IDS_DRAWINFRONT                 159
#define IDS_DRAWINBACK                  160
#define IDS_SAVEERROR                   161
#define IDS_TB_BACKGLASS                162
#define IDS_WRONGFILEVERSION            163
#define IDS_NOPASTEINVIEW               164
#define IDS_FINDLOOPED                  165
#define IDS_FINDFAILED                  166
#define IDS_SETASDEFAULT                167
#define IDR_BALL                        167
#define IDS_FINDFAILED2                 168
#define ID_INSERT_DISPREEL              168
#define IDS_CONTROLPOINT                169
#define IDS_REMOVEMATERIAL              170
#define IDS_CORRUPTFILE                 171
#define IDC_DISPREEL                    171
#define IDS_UNSECURECONTROL1            172
#define IDC_CUR_DISPLCDSEG              172
#define IDS_UNSECURECONTROL2            173
#define IDS_COLLECTION                  174
#define IDS_DEFAULTPHYSICS              175
#define IDS_IMAGE_USED                  176
#define IDS_USED_IN_TABLE               176
#define IDS_LOCK                        177
#define IDS_MISC                        178
#define ID_LOCK                         179
#define IDS_IMAGESIZE                   179
#define IDS_LIGHTSEQ_DESC               180
#define IDR_LIGHT_SEQ                   181
#define IDS_COPY_ELEMENT                181
#define IDS_VISUALS                     182
#define IDS_POSITION                    183
#define IDS_STATE                       184
#define IDS_PHYSICS                     185
#define IDS_TB_PRIMITIVE                186
#define IDS_VISUALS2                    187
#define IDS_POSITION_TRANSLATION        188
#define IDC_FLIPPER_EOS_T_D_A           189
#define IDS_PASTE_ELEMENT               189
#define IDS_PASTE_AT_ELEMENT            190
#define IDS_DELETE_ELEMENTS             191
#define IDS_IMAGE_RAW_SIZE              192
#define IDS_STRING193                   193
#define IDS_SIZE                        193
#define IDS_DRAWING_ORDER_SELECT        200
#define IDR_APPMENU                     201
#define IDC_SOUNDLIST                   201
#define IDC_MATERIAL_LIST               201
#define IDR_POINTMENU                   202
#define IDC_IMPORT                      203
#define IDC_REIMPORT                    204
#define IDB_TOOLBAR                     205
#define IDC_REIMPORTFROM                205
#define IDC_PLAY                        206
#define IDC_DELETE                      207
#define IDC_EXPAND                      207
#define IDC_RENAME                      208
#define IDC_PICTUREPREVIEW              209
#define IDC_EDIT                        209
#define IDC_PAUSE                       209
#define IDC_SNDEXPORT                   209
#define IDC_ROTATEBY                    210
#define IDC_EXPORT                      210
#define IDC_SNDTOBG                     210
#define IDC_CENTERX                     211
#define IDC_CENTERY                     212
#define IDC_SCALEFACTOR                 214
#define IDR_VPACCEL                     216
#define IDC_PROGRESS2                   216
#define IDC_SCALEY                      216
#define IDD_SOUNDDIALOG                 217
#define IDD_IMAGEDIALOG                 218
#define IDI_VPINBALL                    218
#define IDC_STEP                        218
#define IDC_STATUSNAME                  218
#define IDB_BALL                        220
#define IDR_SURFACEMENU                 221
#define IDD_ROTATE                      222
#define IDR_MULTIMENU                   222
#define IDD_SCALE                       223
#define IDC_MATERIAL_COLOR              224
#define IDC_SYSTEM_TIME                 225
#define IDC_VP_WINDOW_WIDTH             226
#define IDC_VP_WINDOW_HEIGHT            227
#define IDD_PROGRESS                    228
#define IDD_PROPTABLE                   229
#define IDD_PROPLIGHT                   231
#define IDD_PROPRAMP                    232
#define IDD_PROPTIMER                   233
#define IDD_PROPFLIPPER                 234
#define IDD_PROPFLIPPER_VISUALS         234
#define IDD_PROPPLUNGER                 235
#define IDD_PROPTEXTBOX                 236
#define IDD_PROPBUMPER                  237
#define IDD_PROPBUMPER_VISUALS          237
#define IDD_PROPTRIGGER                 238
#define IDD_PROPKICKER                  239
#define IDD_PROPDECAL                   240
#define IDD_PROPGATE                    241
#define IDD_PROPSPINNER                 242
#define IDD_PROPPOINT                   243
#define IDD_PROPWALL                    244
#define IDD_CODEVIEW                    245
#define ID_FIND                         245
#define ID_COMPILE                      246
#define IDD_ABOUT                       250
#define IDC_WEBSITE                     250
#define IDC_TRANSSITE                   251
#define IDC_TRANSLATEWEBSITE            251
#define IDC_BLURB                       251
#define IDI_SCRIPT                      252
#define IDC_DESCRIPTION                 252
#define IDC_RULES                       253
#define IDC_CHANGELOG                   254
#define IDD_VIDEO_OPTIONS               255
#define IDC_FULLSCREEN                  256
#define IDD_FONTDIALOG                  256
#define IDC_SIZELIST                    257
#define IDC_SoundList                   258
#define IDC_PhysicsList                 259
#define IDC_SoundListBG                 259
#define IDC_10BIT_VIDEO                 260
#define IDD_KEYS                        261
#define IDC_LEFTFLIPPERBUTTON           262
#define IDD_TRANSLATE                   262
#define IDC_RIGHTFLIPPERBUTTON          264
#define IDB_LOGO                        264
#define IDC_LEFTTILTBUTTON              266
#define IDI_TABLE                       266
#define IDR_SCRIPTMENU                  267
#define IDC_RIGHTTILTBUTTON             268
#define IDD_AUDIO_OPTIONS               268
#define IDC_PLUNGERBUTTON               269
#define IDD_GAMEPAUSE                   269
#define IDC_CENTERTILTBUTTON            270
#define IDD_PROPBACKGLASS               270
#define IDR_CODEVIEWACCEL               271
#define IDD_COLLECTDIALOG               271
#define IDD_COLLECTION                  272
#define IDC_LEFTFLIPPER                 273
#define IDD_PROPDISPREEL                273
#define IDC_RIGHTFLIPPER                274
#define IDD_PROPMULTI                   274
#define IDC_LEFTTILT                    275
#define IDC_RIGHTTILT                   276
#define IDC_CENTERTILT                  277
#define IDR_DISP_REEL                   277
#define IDC_ADDCREDITBUTTON             278
#define IDR_BUMPER1                     278
#define IDR_PRIMITIVE                   278
#define IDC_ADDCREDIT                   279
#define IDR_RUBBER                      279
#define IDC_BUTTON1                     280
#define IDC_IN                          280
#define IDC_STARTGAMEBUTTON             280
#define IDC_GOWEBSITE                   280
#define IDC_ROTATE_APPLY_BUTTON         280
#define IDC_SCALE_APPLY_BUTTON          280
#define IDC_TRANSLATE_APPLY_BUTTON      280
#define IDC_DRAWING_ORDER_UP            280
#define IDC_COL_UP_BUTTON               280
#define IDC_ADD_BUTTON                  280
#define IDC_BROWSE_BUTTON               280
#define IDR_PRIMITIVE1                  280
#define IDR_HITTARGET                   280
#define IDC_BROWSE_BALL_IMAGE           280
#define IDC_UPDATE_ALL_BUTTON           280
#define IDC_DBGLIGHTSBUTTON             280
#define IDC_DEFAULT_COLORS_BUTTON       280
#define IDC_TEST                        280
#define IDC_ITEMLIST                    281
#define IDC_OUT                         281
#define IDC_SENDMAIL                    281
#define IDC_LMAGSAVEBUTTON              281
#define IDC_BROWSE_BALL_DECAL           281
#define IDC_EVENTLIST                   282
#define IDC_OFFSETX                     282
#define IDC_RIGHTMAGNASAVE              282
#define IDC_RMAGSAVEBUTTON              282
#define IDC_OFFSETY                     283
#define IDC_DOWN                        283
#define IDC_MECHTILTBUTTON              283
#define IDC_UP                          284
#define IDC_JOYCUSTOM1                  284
#define IDC_PLAY_MUSIC                  285
#define IDC_OUT2                        285
#define IDR_TABLEMENU                   285
#define IDC_MUSIC_SLIDER                286
#define IDD_TABLEINFO                   286
#define IDC_JOYCUSTOM2                  286
#define IDC_PLAY_SOUND                  287
#define IDC_SQUARE                      287
#define IDD_PROP_NAME                   287
#define IDC_JOYCUSTOM3                  287
#define IDC_SOUND_SLIDER                288
#define IDD_PROP_TIMER                  288
#define IDC_JOYCUSTOM4                  288
#define IDC_STATIC_MUSIC                289
#define IDD_PROPLIGHT_VISUALS           289
#define IDC_STATIC_SOUND                290
#define IDD_PROPLIGHT_POSITION          290
#define IDC_STATIC_SCALEY               291
#define IDD_PROPLIGHT_STATE             291
#define IDD_PROPBUMPER_PHYSICS          292
#define ID_QUIT                         293
#define IDD_PROPBUMPER_STATE            293
#define ID_RESUME                       294
#define ID_DEBUGWINDOW                  295
#define IDD_PHYSICS_OPTIONS             297
#define IDC_VERSION                     302
#define IDC_TRANSWEBSITE                303
#define IDC_TRANSNAME                   304
#define IDC_NEW                         305
#define IDC_TRANSNAME2                  305
#define IDC_CREATEFROMSELECTION         306
#define IDC_NAME                        307
#define IDC_OUTLIST                     309
#define IDC_INLIST                      310
#define IDC_FIRE                        311
#define IDC_SUPPRESS                    312
#define ID_INSERT_LIGHTSEQ              313
#define IDS_TB_LIGHTSEQ                 314
#define IDC_LIGHTSEQ                    315
#define IDS_REPLACEALL                  315
#define IDD_PROPLIGHTSEQ                316
#define IDS_REPLACEALL2                 316
#define IDD_EDITOR_OPTIONS              317
#define IDC_DRAW_DRAGPOINTS             318
#define IDC_DRAW_LIGHTCENTERS           319
#define IDD_PROTECT_DIALOG              320
#define IDM_SAVEASPROTECTED             321
#define IDC_PROTECT_PASSWORD            321
#define IDM_UNLOCKPROTECTED             322
#define IDC_PROTECT_PASSWORD2           322
#define IDC_PROTECT_SCRIPT              323
#define IDC_PROTECT_SAVEAS              324
#define IDC_PROTECT_MANAGERS            325
#define IDC_UNLOCK_PASSWORD             325
#define IDC_PROTECT_COPY                326
#define IDC_PROTECT_TOTALLOCK           327
#define IDD_PROTECT_SHOWPASSWORD        328
#define IDD_UNLOCK_DIALOG               329
#define IDC_PROTECT_VIEWTABLE           329
#define IDS_PERMISSION_ERROR            330
#define IDD_PROPWALL_VISUALS            330
#define IDC_PROTECT_DEBUGGER            330
#define IDS_PROTECT_ONETICKED           331
#define IDD_PROPWALL_PHYSICS            331
#define IDS_PROTECT_PW_ZEROLEN          332
#define IDD_PROPWALL_POSITION           332
#define IDS_PROTECT_PW_MISMATCH         333
#define IDD_PROPGATE_VISUALS            333
#define IDS_UNLOCK_FAILED               334
#define IDD_PROPGATE_POSITION           334
#define IDS_UNLOCK_SUCCESS              335
#define IDD_PROPRAMP_VISUALS            335
#define IDC_TABLENAME                   336
#define IDD_PROPRAMP_POSITION           336
#define IDS_EDITOR                      336
#define IDC_TABLEAUTHOR                 337
#define IDD_PROPFLIPPER_POSITION        337
#define IDS_DEFAULTBALL                 337
#define IDC_EMAIL                       338
#define IDD_PROPFLIPPER_PHYSICS         338
#define IDS_NONE                        338
#define IDC_RELEASE                     339
#define IDS_VALUE                       339
#define IDC_COMBO1                      340
#define IDD_PROPPLUNGER_PHYSICS         340
#define IDC_SCREENSHOT                  340
#define IDS_MAKEACTIVEBALL              340
#define IDC_MonitorCombo                340
#define IDC_FUNCTIONLIST                340
#define IDC_LIGHT_TYPE_CHECKBOX         340
#define IDC_MATERIAL_COMBO              340
#define IDC_LIGHTSCOMBO                 340
#define IDD_PROPSPINNER_VISUALS         341
#define IDS_DEBUGNOCONVERT              341
#define IDC_MATERIAL_COMBO2             341
#define IDB_CHEVRON                     342
#define IDD_PROPSPINNER_POSITION        342
#define IDS_UNDOPASTSAVE                342
#define IDD_PROPSPINNER_PHYSICS         343
#define IDC_ACTIVEX0                    343
#define IDS_LOADING                     343
#define IDD_PROPRAMP_PHYSICS            344
#define IDC_ACTIVEX1                    344
#define IDS_SAVING                      344
#define IDD_PROPTRIGGER_VISUALS         345
#define IDC_ACTIVEX2                    345
#define IDS_AUTOSAVING                  345
#define IDC_ROTATION_EDIT               345
#define IDD_PROPTRIGGER_STATE           346
#define IDC_ACTIVEX3                    346
#define IDS_HANG                        346
#define IDC_ROTATION_EDIT2              346
#define IDC_STAR_RADIUS_EDIT            346
#define IDD_PROPKICKER_VISUALS          347
#define IDC_ACTIVEX4                    347
#define IDC_CUSTOMNAME                  347
#define IDS_PLAY                        347
#define IDC_STAR_THICKNESS_EDIT         347
#define IDD_PROPDECAL_VISUALS           348
#define IDC_CUSTOMVALUE                 348
#define IDS_PAUSE                       348
#define IDD_PROPDECAL_POSITION          349
#define IDC_CUSTOMLIST                  349
#define IDS_STEP                        349
#define IDD_PROPLIGHTSEQ_POSITION       350
#define IDD_PROPLIGHTSEQ_STATE          351
#define IDC_STEPAMOUNT                  351
#define IDD_PROPTEXTBOX_VISUALS         352
#define IDD_PROPTEXTBOX_POSITION        353
#define IDD_PROPTEXTBOX_STATE           354
#define IDD_PROPDISPREEL_VISUALS        355
#define IDC_GUIDE1                      355
#define IDD_PROPDISPREEL_POSITION       356
#define IDD_PROPDISPREEL_STATE          357
#define IDD_PROPTABLE_VISUALS           358
#define IDC_GUIDE2                      359
#define IDD_PROPTABLE_PHYSICS           360
#define IDC_EDITSIZE                    360
#define IDD_PROPTABLE_BALL              361
#define IDC_AUTOSAVE_MINUTES            361
#define IDC_TOOLBARSIZE                 361
#define IDD_PROPBACKGLASS_VISUALS       362
#define IDC_ELEMENT_LIST                362
#define IDC_DRAWING_ORDER_LIST          362
#define IDD_PROPPOINT_POSITION          363
#define IDD_PROPPOINT_VISUALS           364
#define IDC_HANGDETECT                  364
#define IDD_SECURITY_OPTIONS            365
#define IDD_PROPPOINT_VISUALSWTEX       366
#define IDC_PROTECT_SAVEASPROT          367
#define IDD_PROPGATE_PHYSICS            367
#define IDD_DEBUGGER                    368
#define DISPID_SPIN_SUPPORTS            368
#define IDI_PLAY                        369
#define IDI_PAUSE                       370
#define IDI_STEP                        371
#define IDC_JOYDEADZONESLIDER           371
#define IDC_Tex3072                     373
#define IDC_Tex1024                     374
#define IDC_Tex2048                     375
#define IDC_TexUnlimited                376
#define IDC_Layback                     377
#define IDC_LOADED_MESH_TEXT            377
#define IDC_ALPHA_EDIT                  377
#define IDC_SIZE_WIDTH                  377
#define IDC_WIRE_DIAMETER               377
#define IDC_MAX_PRE_FRAMES              377
#define IDC_FADE_SPEED_UP               377
#define IDC_XMAX_EDIT                   377
#define IDC_DIFFUSE_EDIT                377
#define IDC_ALPHA_MASK_EDIT             377
#define IDC_FILENAME_EDIT               377
#define IDC_CALC_HEIGHT_EDIT            377
#define IDC_TARGET_MOVE_SPEED_EDIT      377
#define IDC_THROW_BALLS_SIZE_EDIT       377
#define IDC_THROW_BALL_SIZE_EDIT2       377
#define IDC_DBG_LIGHT_FADE_UP_EDIT      377
#define IDC_HEIGHT_EDIT                 378
#define DISPID_SIDES                    378
#define IDC_GLOSSY_EDIT                 378
#define IDC_ALPHA_EDIT2                 378
#define IDC_FILTERAMOUNT_EDIT           379
#define IDD_PROPKICKER_STATE            379
#define IDC_SPECULAR_EDIT               379
#define IDD_PROPPRIMITIVE_POSITION      380
#define IDC_OPACITY_EDIT                380
#define IDD_PROPPRIMITIVE_VISUALS       381
#define IDD_PROPRAMP_VISUALS1           382
#define IDD_PROPPLUNGER_VISUALS         382
#define IDR_EXAMPLE_TABLE               383
#define IDC_ARASlider                   384
#define IDR_TABLE1                      384
#define IDR_EXAMPLETABLE                384
#define IDC_PRIMITIVE                   385
#define IDC_StretchNo                   386
#define IDR_REGISTRY1                   386
#define IDC_StretchYes                  387
#define IDR_REGISTRY2                   387
#define IDC_StretchMonitor              388
#define DISPID_IMAGEMAPPING             389
#define IDD_PROPTABLE_LIGHTSOURCES      390
#define IDD_SEARCH_SELECT_ELEMENT       391
#define IDD_DRAWING_ORDER               392
#define IDR_Flasher                     393
#define IDC_GLOBAL_REFLECTION_CHECK     394
#define IDC_ENABLE_OFF_LIGHTING         394
#define IDC_ENABLE_RAMP_LIGHTING        394
#define IDC_ENABLE_AA                   394
#define IDR_REGISTRY3                   394
#define IDC_BALL_THROWING               394
#define IDC_ENABLE_MOUSE_PLAYER         394
#define IDC_ENABLED                     394
#define IDC_FLIPPER_ENABLED             394
#define IDC_DIFFUSE_CHECK               394
#define IDC_SHOW_BULB_MESH              394
#define IDC_FALL_THROUGH_HOLE           394
#define IDC_PRIMITIVE_IS_TOY            395
#define IDC_ENABLE_FXAA                 395
#define IDR_REGISTRY4                   395
#define IDC_ENABLE_AO                   396
#define IDC_SIZE_HEIGHT                 397
#define IDC_DEPTH_BIAS                  397
#define IDC_YMAX_EDIT                   397
#define IDC_WIRE_DISTX                  398
#define IDC_STATIC_RENDERING_CHECK      398
#define IDC_ON_LIGHT_LIGHTMAP           398
#define IDC_AA_ALL_TABLES               398
#define IDC_GLOBAL_ALPHA_ACC            398
#define IDC_OPACITY_CHECK               398
#define IDC_JOYMECHTILTCOMBO            399
#define IDC_FLASHER                     399
#define IDC_ADDCREDITBUTTON2            400
#define IDD_DIMENSION_CALCULATOR        400
#define IDC_ADDCREDIT2                  401
#define IDC_ADDCREDITKEY2               401
#define IDC_EXITGAME                    402
#define IDC_EXITGAMEBUTTON              403
#define IDC_FRAMECOUNTBUTTON            404
#define IDC_FRAMECOUNT                  405
#define IDC_VOLDOWNBUTTON               406
#define IDC_VOLUMEDN                    407
#define IDC_VOLUPBUTTON                 408
#define IDC_VOLUMEUP                    409
#define IDC_DEBUGBALLSBUTTON            410
#define IDC_DEBUGBALL                   411
#define IDC_JOYCUSTOM1BUTTON            412
#define IDC_JOYCUSTOM2BUTTON            413
#define IDC_JOYCUSTOM3BUTTON            414
#define IDC_JOYCUSTOM3BUTTON2           415
#define IDC_JOYCUSTOM4BUTTON            415
#define IDC_JOYCUSTOM1COMBO             416
#define IDC_JOYCUSTOM2COMBO             417
#define IDC_ROTATE_UNDO_BUTTON          417
#define IDC_SCALE_UNDO_BUTTON           417
#define IDC_TRANSLATE_UNDO_BUTTON2      417
#define IDC_TRANSLATE_UNDO_BUTTON       417
#define IDC_DRAW_ORDER_UP               417
#define IDC_DRAWING_ORDER_DOWN          417
#define IDC_COL_DOWN_BUTTON             417
#define IDC_CLONE_BUTTON                417
#define IDC_JOYCUSTOM3COMBO             418
#define IDC_DRAW_ORDER_DOWN             418
#define IDC_JOYCUSTOM4COMBO             419
#define IDC_JOYDEBUGCOMBO               420
#define IDC_ALPHA_SLIDER                420
#define IDC_GLOBAL_TRAIL_CHECK          421
#define IDC_VP_WIDTH                    421
#define IDC_DEBUGGERBUTTON              421
#define IDC_VP_HEIGHT                   422
#define IDC_DEBUGGER                    422
#define IDC_TABLE_DIM_LIST              423
#define IDC_JOYDEBUGGERCOMBO            423
#define IDC_DYNAMIC_AO                  424
#define IDC_FORCE_ANISO                 425
#define IDC_WIRE_DISTY                  425
#define IDC_SCALE_BULB_MESH             425
#define IDC_MATERIAL_COMBO3             426
#define IDC_GLOBAL_3DSTEREO             427
#define IDC_TWO_WAY_CHECK               427
#define IDC_3D_STEREO_MS                428
#define IDC_3D_STEREO_ZPD               429
#define IDC_HALO_EDIT                   429
#define IDC_ENABLE_NUDGE_FILTER         430
#define IDAPPLY                         430
#define IDC_BULB_MODULATE_VS_ADD        431
#define IDC_CHECK1                      431
#define IDC_GROUP_CHECK                 431
#define IDC_DISABLE_LIGHTING            431
#define IDC_PROP_FLOAT_CHECK            431
#define EDITOR_CHECK                    431
#define IDC_SHOW_IN_EDITOR_CHECK        431
#define IDC_CONVERT_COORD_CHECK         431
#define IDC_LEGACYMODE                  431
#define IDC_REFLECT_ELEMENTS_CHECK      431
#define IDC_RAMP_REFLECT_ENABLED_CHECK  431
#define IDC_BUMPER_REFLECT_ENABLED_CHECK 431
#define IDC_SPINNER_REFLECT_ENABLED_CHECJ 431
#define IDC_SPINNER_REFLECT_ENABLED_CHECK 431
#define IDC_FLIPPER_REFLECT_ENABLED_CHECK 431
#define IDC_GATE_REFLECT_ENABLED_CHECK  431
#define IDC_PLUNGER_REFLECT_ENABLED_CHECK 431
#define IDC_TRIGGER_REFLECT_ENABLED_CHECK 431
#define IDC_CVP_CHKBOX_SHOWAUTOCOMPLETE 431
#define IDC_USE_NVIDIA_API_CHECK        431
#define IDC_DBG_MATERIAL_OPACITY_ACTIVE_CHECK 431
#define IDC_AUDIOOPT_3D_SOUND           431
#define IDC_CHECK_ROTATE_CENTER         431
#define IDC_CHECK_SCALE_CENTER          431
#define IDC_OVERWRITE_MATERIAL_SETTINGS 432
#define IDC_LIGHT_FALLOFF_POWER         432
#define IDC_TARGET_LEGACY_MODE_CHECK    433
#define IDC_MODULATE_VS_ADD             433
#define IDC_INTENSITY_SCALE_LIGHT       434
#define IDC_OVERWRITE_MATERIAL_SETTINGS2 434
#define IDC_TARGET_ISDROPPED_CHECK      435
#define IDC_INTENSITY_SCALE_FLASHER     435
#define IDC_DAYNIGHT_SLIDER             436
#define IDC_FADE_SPEED_DOWN             437
#define IDC_BALL_DECAL_MODE             438
#define IDC_FS_INCL                     439
#define IDC_FS_FOV                      440
#define IDC_FS_LB                       441
#define IDC_FS_ROT                      442
#define IDC_FS_XS                       443
#define IDC_FS_YS                       444
#define IDC_FS_ZS                       445
#define IDC_FS_XT                       446
#define IDC_FS_YT                       447
#define IDC_FS_ZT                       448
#define IDC_BG_SET                      449
#define IDC_BLOOM_STRENGTH              450
#define IDC_BULB_INTENSITY_SCALE        451
#define IDC_TEX_COMPRESS                452
#define IDC_IMAGE_MODE                  453
#define IDC_EDGE_FACTOR_UI              454
#define IDC_REFLECT_ON_BALLS            455
#define IDC_NUDGE_STRENGTH              456
#define IDC_COLOR_FULL                  457
#define IDC_REEL_VISIBLE                458
#define IDC_BG_NIGHT_DAY                459
#define IDC_CORRECTION_X                460
#define IDC_CORRECTION_Y                461
#define IDC_MAT_ELASTICITY_FALLOFF      461
#define IDC_ASPECT_RATIO_EDIT           461
#define IDC_FXAACB                      462
#define IDC_ABOUT_VERSION               463
#define DISPID_PluFrames                464
#define DISPID_Width                    465
#define DISPID_ZAdjust                  466
#define DISPID_RodDiam                  467
#define DISPID_RingDiam                 468
#define DISPID_RingThickness            469
#define DISPID_SpringDiam               470
#define DISPID_TipShape                 471
#define DISPID_SpringGauge              472
#define DISPID_SpringLoops              473
#define DISPID_RingGap                  474
#define DISPID_SpringEndLoops           475
#define IDC_SCALE_FX_DMD                476
#define IDC_REL_POSITION_RADIO          477
#define IDC_ABS_POSITION_RADIO          478
#define IDC_CHECK3                      479
#define IDC_CENTER_MESH                 479
#define IDC_RUBBER_REFLECT_ENABLED_CHECK 479
#define IDC_CVP_CHKBOX_HELPWITHDWELL    479
#define IDC_OVERWRITE_BALL_IMAGE_CHECK  479
#define IDC_DBG_LIGHT_OFF_CHECK         479
#define IDC_IMPORT_MATERIAL             480
#define IDC_COLLISION_REDUCTION_FACTOR  481
#define IDC_DEFAULTS                    482
#define IDC_PRIM_REFLECT_ENABLE_CHECK   483
#define IDC_WALL_REFLECT_ENABLED_CHECK  484
#define IDC_CHECK5                      488
#define IDC_DBG_LIGHT_BLINKING_CHECK    488
#define IDC_SM3DSOUND                   488
#define IDC_DYNAMIC_DN                  489
#define IDC_DN_LONGITUDE                490
#define IDC_DN_LATITUDE                 491
#define IDC_DISABLE_DWM                 492
#define IDC_START_VP_FILE_DIALOG        493
#define IDC_BLEND_DISABLE_LIGHTING      494
#define IDC_ENABLE_LEGACY_NUDGE         495
#define IDC_BLEND_DISABLE_LIGHTING_FROM_BELOW 496
#define IDC_BALLDECALMODE               497
#define IDC_JOYLFLIPCOMBO               501
#define IDC_JOYRFLIPCOMBO               502
#define IDC_JOYPLUNGERCOMBO             503
#define IDC_JOYLMAGNACOMBO              504
#define IDC_JOYRMAGNACOMBO              505
#define IDC_JOYADDCREDITCOMBO           506
#define IDC_JOYADDCREDIT2COMBO          507
#define IDC_JOYSTARTCOMBO               508
#define IDC_JOYEXITCOMBO                509
#define IDC_JOYFPSCOMBO                 510
#define IDC_JOYVOLUPCOMBO               511
#define IDC_JOYVOLDNCOMBO               512
#define IDC_PLUNGERAXIS                 513
#define IDC_DefaultLayout               514
#define IDC_ReversePlunger              515
#define IDC_JOYLTILTCOMBO               516
#define IDC_JOYCTILTCOMBO               517
#define IDC_JOYRTILTCOMBO               518
#define IDC_UDAXISCOMBO                 519
#define IDC_LRAXISCOMBO                 520
#define IDC_UDAXISGAIN                  521
#define IDC_LRAXISGAIN                  522
#define IDC_UDAXISFLIP                  523
#define IDC_LRAXISFLIP                  524
#define IDC_GLOBALACCEL                 525
#define IDC_GLOBALNMOUNT                526
#define IDC_GLOBALROTATION              527
#define IDC_GLOBALJOLT                  528
#define IDC_CBGLOBALROTATION            529
#define IDC_CBGLOBALJOLT                530
#define IDC_JOYPMBUYIN                  531
#define IDC_JOYPMCOIN3                  532
#define IDC_JOYPMCOIN4                  533
#define IDC_JOYPMCOINDOOR               534
#define IDC_JOYPMCANCEL                 535
#define IDC_JOYPMDOWN                   536
#define IDC_JOYPMUP                     537
#define IDC_JOYPMENTER                  538
#define IDC_DEADZONEAMT                 539
#define IDC_CBGLOBALTILT                540
#define IDC_GLOBALTILT                  541
#define IDC_3D_STEREO                   542
#define IDC_DisableESC_CB               542
#define IDC_3D_STEREO_OFS               543
#define IDC_3D_STEREO_Y                 544
#define IDC_ADAPTIVE_VSYNC              545
#define IDC_STATIC_SOUNDDEVICE          546
#define IDD_PROPTABLE_PHYSICS2          547
#define IDC_STATIC_SOUNDDEVICE2         547
#define IDD_PROPFLASHER_POSITION        548
#define IDS_DIMENSIONSSLOPE             549
#define IDD_PROPFLASHER_VISUALS         549
#define IDS_LIGHTSOURCES                550
#define IDD_PROPRAMP_PHYSICS1           550
#define IDD_PROPPRIMITIVE_PHYSICS       550
#define IDS_INPUT                       551
#define IDS_UNHIDEALL                   552
#define IDS_HIDE                        553
#define IDC_MODIFY3DSTEREO              554
#define IDC_DMD2                        555
#define IDC_ADDBLEND                    556
#define IDC_DMD                         557
#define IDC_LIGHTAMBIENT                558
#define IDC_LIGHT0EMISSION              559
#define IDC_LIGHTHEIGHT                 564
#define IDC_LIGHTRANGE                  565
#define IDC_ENVEMISSIONSCALE            566
#define IDC_LIGHTEMISSIONSCALE          567
#define IDC_AOSCALE                     568
#define IDC_TABLESOUNDVOLUME            579
#define IDC_TABLEMUSICVOLUME            580
#define IDS_PLAYFIELD                   581
#define IDD_PROPTABLE_USER              582
#define IDS_TABLE_USER                  583
#define IDC_TABLEAVSYNC                 585
#define IDC_SOFTWARE_VP                 586
#define IDC_TEXT_INTENSITY              587
#define IDC_GLOBAL_DAYNIGHT             588
#define IDC_AUTOSAVE                    589
#define IDD_PROPPOINT_POSITION_WITHZ    601
#define IDD_PROPRUBBER_PHYSICS          602
#define IDC_RUBBER                      602
#define IDD_PROPRUBBER_POSITION         603
#define IDD_PROPRUBBER_VISUALS          604
#define IDD_MATERIALDIALOG              605
#define IDB_BITMAP1                     608
#define IDB_RINGENVMAP                  609
#define IDB_BITMAP2                     610
#define IDB_BUMPERCAP                   610
#define IDC_GLOSSY_IMGLERP_EDIT         611
#define IDB_KICKER_HOLE_WOOD            612
#define IDB_BITMAP3                     613
#define IDB_KICKER_CUP                  613
#define IDR_POINTMENU_SMOOTH            614
#define IDB_AO_DITHER                   615
#define IDC_TRANSMISSION_SCALE          617
#define IDC_EDGEALPHA_EDIT              618
#define IDD_MESH_IMPORT_DIALOG          619
#define IDD_PROPHITTARGET_VISUALS       620
#define IDD_PROPHITTARGET_POSITION      621
#define IDD_PROPHITTARGET_PHYSICS       622
#define IDD_DBGLIGHTDIALOG              623
#define IDD_DBGMATERIALDIALOG           624
#define IDC_BG_FSS                      625
#define IDC_ENABLE_CAMERA_FLY_AROUND    626
#define IDD_SOUND_POSITION              629
#define IDD_SOUND_POSITION_DIALOG       629
#define IDR_BLANK_TABLE                 630
#define IDB_KICKER_WILLIAMS             640
#define IDB_KICKER_GOTTLIEB             645
#define IDB_BITMAP4                     646
#define IDB_KICKER_T1                   646
#define IDC_CVP_BUT_CANCEL              701
#define IDC_CVP_BUT_OK                  702
#define IDC_CVP_BUT_COL_COMPS           703
#define IDC_CVP_BUT_COL_SUBS            704
#define IDC_CVP_BUT_COL_VBS             705
#define IDC_CVP_BUT_COL_COMMENTS        706
#define IDC_CVP_BUT_COL_LITERALS        707
#define IDC_CVP_BUT_COL_VPCORE          708
#define IDC_CVP_CHECKBOX_VBS            709
#define IDC_CVP_CHKB_SUBS               710
#define IDC_CVP_TITLE                   711
#define IDC_CVP_CHKB_COMP               712
#define IDC_CVP_CHKB_LITERALS           713
#define IDC_CVP_CHKB_COMMENTS           714
#define IDC_CVP_CHKB_VPCORE             715
#define IDC_CVP_EXAMPLE_COMPS           716
#define IDC_CVP_BUT_FONT_COMPS          716
#define IDC_CVP_BUT_FONT_SUBS           717
#define IDC_CVP_BUT_FONT_VBS            718
#define IDC_DELETE_MATERIAL             718
#define IDC_CVP_BUT_FONT_COMMENTS       719
#define IDC_DELETE_SOUND                719
#define IDC_CVP_BUT_FONT_LITERALS       720
#define IDC_DELETE_IMAGE                720
#define IDC_CVP_BUT_FONT_VPCORE         721
#define IDC_DELETE_COLLECTION           721
#define IDC_CVP_CHKBOX_DISPLAYDWELL     722
#define IDC_CVP_BUT_COL_EVERYTHINGELSE  724
#define IDC_BALL_IMAGE_EDIT             724
#define IDC_CVP_BUT_FONT_EVERYTHINGELSE 725
#define IDC_BALL_DECAL_EDIT             725
#define IDC_THROW_BALLS_ALWAYS_ON_CHECK 725
#define IDC_TARGET_RAISE_DELAY_EDIT     726
#define IDC_CVP_BUT_COL_BACKGROUND      727
#define IDC_CHECK2                      727
#define IDC_STATIC_BULB_MESH            727
#define IDC_IMPORT_ANIM_SEQUENCE        727
#define IDC_DBG_LIGHT_ON_CHECK          727
#define IDC_DEFAULT_GROUP_COLLECTION_CHECK 727
#define IDC_CVP_EDIT_AUTOCHARS          728
#define IDC_CVP_EDIT_MOUSEDWELL         729
#define IDC_MAT_ELASTICITY              731
#define IDC_MAT_FRICTION                732
#define IDC_MAT_SCATTER_ANGLE           733
#define IDC_MATERIAL_COMBO4             734
#define IDC_RING_VISIBLE                735
#define IDC_SKIRT_VISIBLE               736
#define IDC_DOF_CONTACTORS              737
#define IDC_DOF_KNOCKER                 738
#define IDC_DOF_CHIMES                  739
#define IDC_DOF_BELL                    740
#define IDC_DOF_GEAR                    741
#define IDC_DOF_SHAKER                  742
#define IDC_DOF_FLIPPERS                743
#define IDC_DOF_TARGETS                 744
#define IDC_DOF_DROPTARGETS             745
#define IDC_DOF_FORCEDISABLE            746
#define IDC_DBG_LIGHT_FALLOFF           748
#define IDC_DBG_LIGHT_FALLOFF_POWER     749
#define IDC_DBG_LIGHT_FADE_DOWN_EDIT    754
#define IDC_DBG_MATERIAL_GLOSSY_IMGLERP_EDIT 755
#define IDC_ASPECT_RATIO_GROUP          756
#define IDC_MATERIALCOMBO               757
#define IDC_DBG_MATERIALCOMBO           757
#define IDC_DBG_METAL_MATERIAL_CHECK    758
#define IDC_DBG_MATERIAL_BASE_WRAP_EDIT 759
#define IDC_DBG_MATERIAL_SHININESS_EDIT 761
#define IDC_DBG_MATERIAL_EDGE_EDIT      762
#define IDC_DBG_MATERIAL_OPACITY_AMOUNT_EDIT 763
#define DBG_MATERIAL_OPACITY_EDGE_EDIT  764
#define IDC_BUTTON2                     765
#define IDC_DBG_MATERIALS_BUTTON        765
#define IDC_DBG_BULB_MODULATE_VS_ADD    766
#define IDC_DBG_TRANSMISSION_SCALE      767
#define IDC_STATIC_GLOSSY_IMGLERP       768
#define IDC_EDIT1                       769
#define IDC_OK                          770
#define IDC_STATIC_ALPHA                771
#define IDC_STATIC_BASE_COLOR           772
#define IDC_STATIC_GLOSSY_LAYER         773
#define IDC_STATIC_CLEARCOAR_LAYER      774
#define IDC_STATIC_OPACITY              775
#define IDC_STATIC_PHYSICS              776
#define IDC_STATIC_WRAP                 777
#define IDC_STATIC_SHININESS            778
#define IDC_STATIC_EDGE_BRIGHTNESS      779
#define IDC_STATIC_AMOUNT               780
#define IDC_STATIC_EDGE_OPACITY         781
#define IDC_STATIC_WRAP_TEXT            782
#define IDC_STATIC_GLOSSY_TEXT          783
#define IDC_STATIC_SHININESS_TEXT       784
#define IDC_STATIC_CLEARCOAT_TEXT       785
#define IDC_STATIC_BRIGHTNESS_TEXT      786
#define IDC_STATIC_EDGE_OPACITY_TEXT    787
#define IDC_STATIC_PHY_ELASTICITY       788
#define IDC_STATIC_PHY_ELASTICITY_FALLOFF 789
#define IDC_STATIC_PHY_FRICTION         790
#define IDC_STATIC_PHY_SCATTER_ANGLE    791
#define IDC_PRIMITIVE_ENABLE_BACKFACES  792
#define IDC_FSS_INCL                    793
#define IDC_FSS_FOV                     794
#define IDC_FSS_LB                      795
#define IDC_FSS_ROT                     796
#define IDC_FSS_XS                      797
#define IDC_FSS_YS                      798
#define IDC_FSS_ZS                      799
#define IDC_FSS_XT                      800
#define IDC_FSS_YT                      801
#define IDC_FSS_ZT                      802
#define IDC_LOCKBAR                     803
#define IDC_LOCKBARBUTTON               804
#define IDC_JOYLOCKBARCOMBO             805
#define IDC_SNDPOSITION                 806
#define IDC_SPT_TABLE                   807
#define IDC_SPT_BACKGLASS               808
#define IDC_AUD_BALANCE                 809
#define IDC_AUD_VOLUME                  810
#define IDC_RADIO_SND3DFRONTISFRONT     810
#define IDC_SPT_3D                      811
#define IDC_RADIO_SND3D2CH              811
#define IDC_EDIT2                       811
#define IDC_AUD_FADER                   812
#define IDC_RADIO_SND3DFRONTISREAR      812
#define IDC_RADIO_SND3DALLREAR          813
#define IDC_EDIT_BALANCE                813
#define IDC_RADIO_SND3D6CH              814
#define IDC_EDIT_FADER                  814
#define IDC_EDIT5                       815
#define IDC_EDIT_VOL                    815
#define IDC_DBG_MATERIAL_THICKNESS_EDIT 816
#define IDC_THICKNESS_EDIT              817
#define IDC_STATIC_THICKNESS            818
#define IDC_STATIC_THICKNESS_TEXT       819
#define DISPID_Gate_Height1             1142
#define DISPID_Image                    1500
#define DISPID_Image2                   1501
#define DISPID_Surface                  1502
#define DISPID_Shape                    1503
#define DISPID_UserValue                1504
#define DISPID_Image3                   1505
#define DISPID_Sound                    1506
#define DISPID_Collection               1507
#define DISPID_Image4                   1508
#define DISPID_Image5                   1509
#define DISPID_Image6                   1510
#define DISPID_Image7                   1511
#define DISPID_Image8                   1512
#define IDC_MESH_FILENAME_EDIT          1601
#define IDC_LOAD_MESH_BUTTON            1602
#define IDC_EXPORT_MESH_BUTTON          1603
#define IDC_IMPORT_PHYSICS_BUTTON       1604
#define IDC_EXPORT_PHYSICS_BUTTON       1605
#define IDC_BALL_REFLECTION             1700
#define IDC_REFLECTION_EDIT             1701
#define IDC_BALL_TRAIL                  1704
#define IDC_TRAIL_EDIT                  1705
#define IDB_ENV                         1706
#define IDC_REFLECTION_PLAYFIELD        1707
#define IDC_PLAYFIELD_ELASTICITY        1708
#define IDC_PLAYFIELD_ELASTICITY_FALLOFF 1709
#define IDC_PLAYFIELD_SCATTER           1710
#define IDC_TABLE_FILENAME              1711
#define IDC_BALLPLAYFIELD_REFLECTION    1712
#define IDC_BALLPLAYFIELD_REFLECTION2   1713
#define IDC_BULBINTENSITYSCALE          1713
#define IDC_BG_COMBOBOX                 1714
#define ID_SHOWTOOLTIP                  4001
#define ID_SHOWAUTOCOMPLETE             4001
#define ID_SCRIPT_PREFERENCES           4002
#define ID_EXPORT_BACKGLASSPOV          4003
#define ID_FILE_IMPORT                  4004
#define ID_IMPORT_BACKGLASSPOV          4005
#define ID_IMPORT_BACKDROPPOV           4006
#define ID_EXPORT_BACKDROPPOV           4007
#define ID_WALLMENU_COPY                4016
#define ID_WALLMENU_PASTE               4017
#define ID_TABLEMENU_COPY               4018
#define ID_TABLEMENU_PASTE              4019
#define ID_NEW_BLANKTABLE               4020
#define ID_NEW_EXAMPLETABLE             4021
#define IDM_NEW                         32768
#define IDM_OPEN                        32769
#define IDM_CLOSE                       32770
#define IDM_SAVE                        32771
#define IDM_SAVEAS                      32772
#define ID_SCRIPT_SHOWIDE               32773
#define ID_ADDPOINT                     32775
#define ID_POINTMENU_SMOOTH             32776
#define ID_WINDOW_TILE                  32783
#define ID_WINDOW_CASCADE               32784
#define ID_WINDOW_ARRANGEICONS          32785
#define ID_TABLE_PLAY                   32786
#define IDC_COPY                        32787
#define IDC_PASTE                       32788
#define ID_FILE_EXPORT_BLUEPRINT        32790
#define ID_TABLE_SOUNDMANAGER           32792
#define ID_TABLE_IMAGEMANAGER           32793
#define ID_EDIT_UNDO                    32794
#define ID_EDIT_PROPERTIES              32795
#define ID_POINTMENU_SLINGSHOT          32796
#define ID_WALLMENU_FLIP                32797
#define ID_WALLMENU_MIRROR              32798
#define ID_WALLMENU_ROTATE              32799
#define ID_WALLMENU_SCALE               32800
#define ID_WALLMENU_ADDPOINT            32801
#define ID_HELP_ABOUT                   32802
#define ID_EDIT_SCRIPT                  32803
#define ID_EDIT_VIDEOOPTIONS            32804
#define ID_TABLE_FONTMANAGER            32805
#define ID_EDIT_KEYS                    32806
#define ID_WALLMENU_TRANSLATE           32807
#define ID_EDIT_COPY                    32811
#define ID_EDIT_CUT                     32813
#define ID_EDIT_PASTE                   32814
#define ID_EDIT_AUDIOOPTIONS            32815
#define ID_EDIT_PHYSICSOPTIONS          32816
#define ID_EDIT_BACKGLASSVIEW           32817
#define ID_DELETE                       32818
#define ID_EDIT_FINDNEXT                32819
#define ID_TABLE_COLLECTIONMANAGER      32821
#define ID_FILE_EXIT                    32822
#define ID_SAVE                         32829
#define ID_REPLACE                      32830
#define ID_EDIT_EDITOROPTIONS           32831
#define IDC_PASTEAT                     32836
#define ID_TABLE_TABLEINFO              32838
#define ID_PREFERENCES_SECURITYOPTIONS  32839
#define ID_INSERT_PRIMITIVE             32842
#define ID_LAYER_LAYER1                 32849
#define ID_LAYER_LAYER2                 32850
#define ID_LAYER_LAYER3                 32851
#define ID_LAYER_LAYER4                 32852
#define ID_WALLMENU_ASSIGNTO            32853
#define ID_ASSIGNTO_LAYER1              32854
#define ID_ASSIGNTO_LAYER2              32855
#define ID_ASSIGNTO_LAYER3              32856
#define ID_ASSIGNTO_LAYER4              32857
#define ID_ASSIGNTO_LAYER5              32858
#define ID_ASSIGNTO_LAYER6              32859
#define ID_ASSIGNTO_LAYER7              32860
#define ID_ASSIGNTO_LAYER8              32861
#define ID_LAYER_LAYER5                 32862
#define ID_LAYER_LAYER6                 32863
#define ID_LAYER_LAYER7                 32864
#define ID_LAYER_LAYER8                 32865
#define ID_ASSIGNTO_MERGETOLAYER1       32866
#define ID_LAYER_MERGEALL               32867
#define ID_WALLMENU_SELECTALL           32868
#define ID_WALLMENU_SELECTNONE          32869
#define ID_LAYER_TOGGLEALL              32874
#define ID_EDIT_SEARCH                  32875
#define ID_SELECT_ELEMENT               32876
#define ID_EDIT_DRAWINGORDER_HIT        32879
#define ID_EDIT_DRAWINGORDER_SELECT     32880
#define ID_EDIT_COMMENT                 32882
#define ID_ADD_COMMENT                  32883
#define ID_EDIT_UNCOMMENT               32886
#define ID_REMOVE_COMMENT               32888
#define ID_INSERT_FLASHER               32890
#define ID_TABLE_DIMENSIONMANAGER       32894
#define ID_VIEW_SOLID                   32895
#define ID_VIEW_OUTLINE                 32896
#define ID_VIEW_GRID                    32897
#define ID_VIEW_BACKDROP                32898
#define IDC_GRID_SIZE                   32899
#define ID_INSERT_RUBBER                32990
#define ID_TABLE_MATERIALMANAGER        32991
#define IDM_MATERIAL_EDITOR             32992
#define IDM_IMAGE_EDITOR                32993
#define IDM_SOUND_EDITOR                32994
#define IDM_COLLECTION_EDITOR           32995
#define IDC_EFFECT_COMBO                32996
#define ID_TABLE_CAMERAMODE             32997
#define ID_EDIT_SETDEFAULTPHYSICS       32998
#define ID_EDIT_LOCK                    32999
#define ID_EXPORT_TABLEMESH             33002
#define ID_ADD_CTRL_POINT               33003
#define ID_ADD_SMOOTH_CTRL_POINT        33004
#define DZVALUE                         65535
#define DZName                          65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        647
#define _APS_NEXT_COMMAND_VALUE         4022
#define _APS_NEXT_CONTROL_VALUE         820
#define _APS_NEXT_SYMED_VALUE           188
#endif
#endif
