// license:GPLv3+

#include "core/stdafx.h"
#include "vpx-test.h"

#include "parts/pintable.h"
#include "utils/fileio.h"
#include "utils/BiffReader.h"
#include "utils/BiffWriter.h"

#include "pole/pole.h"

#include "doctest.h"

#include <objbase.h>
#include <filesystem>
#include <set>

// Temp folder for files generated by the tests (under the build output's test-assets)
static std::filesystem::path GetTmpDir()
{
   const std::filesystem::path dir = GetAssetPath() / "tmp";
   std::filesystem::create_directories(dir);
   return dir;
}

static vector<uint8_t> ToBytes(const string &str) { return vector<uint8_t>(str.begin(), str.end()); }

// Reads an entire POLE stream, checks the stream exists and could be fully read
static vector<uint8_t> ReadPoleStream(POLE::Storage &storage, const string &name)
{
   POLE::Stream stream(&storage, name);
   REQUIRE(!stream.fail());
   vector<uint8_t> data(static_cast<size_t>(stream.size()));
   if (!data.empty())
      CHECK(stream.read(data.data(), static_cast<uint64_t>(data.size())) == data.size());
   return data;
}

// Returns the full path of every stream in the storage (e.g. "GameStg/GameData")
static std::set<string> GetStreamSet(POLE::Storage &storage)
{
   std::set<string> result;
   for (const string &name : storage.GetAllStreams("/"))
      result.insert(!name.empty() && name[0] == '/' ? name.substr(1) : name);
   return result;
}

// Byte-compares every stream of two OLE container files, except the listed volatile streams
static void CompareStorageFiles(const std::filesystem::path &fileA, const std::filesystem::path &fileB, const std::initializer_list<string> &volatileStreams)
{
   POLE::Storage storageA(fileA.string().c_str());
   POLE::Storage storageB(fileB.string().c_str());
   REQUIRE(storageA.open());
   REQUIRE(storageB.open());
   const std::set<string> streamsA = GetStreamSet(storageA);
   CHECK(streamsA == GetStreamSet(storageB));
   for (const string &name : streamsA)
   {
      if (std::find(volatileStreams.begin(), volatileStreams.end(), name) != volatileStreams.end())
         continue;
      INFO("Comparing stream '", name, "'");
      CHECK(ReadPoleStream(storageA, name) == ReadPoleStream(storageB, name));
   }
   storageA.close();
   storageB.close();
}

// Reads a stream from an OLE container using the Windows native structured storage API.
// This is an oracle validating that files written by POLE conform to the OLE format
// (and therefore remain readable by older VPX versions and third-party tools).
static vector<uint8_t> NativeReadStream(const std::filesystem::path &file, const wchar_t *storageName, const wchar_t *streamName)
{
   vector<uint8_t> result;
   CComPtr<IStorage> root;
   if (FAILED(StgOpenStorageEx(file.wstring().c_str(), STGM_READ | STGM_SHARE_DENY_WRITE, STGFMT_STORAGE, 0, nullptr, nullptr, IID_IStorage, reinterpret_cast<void **>(&root))))
      return result;
   CComPtr<IStorage> sub;
   if (FAILED(root->OpenStorage(storageName, nullptr, STGM_READ | STGM_SHARE_EXCLUSIVE, nullptr, 0, &sub)))
      return result;
   CComPtr<IStream> stream;
   if (FAILED(sub->OpenStream(streamName, nullptr, STGM_READ | STGM_SHARE_EXCLUSIVE, 0, &stream)))
      return result;
   STATSTG stat;
   if (FAILED(stream->Stat(&stat, STATFLAG_NONAME)))
      return result;
   result.resize(static_cast<size_t>(stat.cbSize.QuadPart));
   ULONG bytesRead = 0;
   if (!result.empty() && (FAILED(stream->Read(result.data(), static_cast<ULONG>(result.size()), &bytesRead)) || bytesRead != result.size()))
      result.clear();
   return result;
}

// Enumerates the entry names of a native structured storage
static std::set<wstring> NativeStorageEntries(IStorage *storage)
{
   std::set<wstring> names;
   CComPtr<IEnumSTATSTG> enumerator;
   if (FAILED(storage->EnumElements(0, nullptr, 0, &enumerator)))
      return names;
   STATSTG stat;
   while (enumerator->Next(1, &stat, nullptr) == S_OK)
   {
      names.insert(stat.pwcsName);
      CoTaskMemFree(stat.pwcsName);
   }
   return names;
}


TEST_CASE("POLE structured storage")
{
   std::error_code ec;

   SUBCASE("round-trip of small, large and nested streams")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-basic.vpx";
      std::filesystem::remove(file, ec);

      vector<uint8_t> big(64 * 1024); // Large stream, stored in the regular FAT
      for (size_t i = 0; i < big.size(); ++i)
         big[i] = static_cast<uint8_t>(i * 31 + 17);
      string smallStr = "Small stream, stored in the mini FAT"s;

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true)); // Write access, create, 4K sectors (as used by PinTable::Save)
         POLE::Stream bigStream(&storage, "GameStg/GameData", true);
         CHECK(bigStream.write(big.data(), big.size()) == big.size());
         POLE::Stream smallStream(&storage, "TableInfo/TableName", true);
         CHECK(smallStream.write(reinterpret_cast<unsigned char *>(smallStr.data()), smallStr.size()) == smallStr.size());
         bigStream.flush(); // Flushes the storage header, allocation tables and directory tree
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK(storage.result() == POLE::Storage::Ok);
         CHECK(storage.isDirectory("GameStg"));
         CHECK(ReadPoleStream(storage, "GameStg/GameData") == big);
         CHECK(ReadPoleStream(storage, "TableInfo/TableName") == ToBytes(smallStr));
         CHECK(GetStreamSet(storage) == std::set<string> { "GameStg/GameData"s, "TableInfo/TableName"s });
         storage.close();
      }
   }

   SUBCASE("incremental update of an existing file")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-update.vpx";
      std::filesystem::remove(file, ec);

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true));
         for (const char *name : { "a", "b", "c" })
         {
            POLE::Stream stream(&storage, std::format("Stg/{}", name), true);
            string content = "content of "s + name;
            CHECK(stream.write(reinterpret_cast<unsigned char *>(content.data()), content.size()) == content.size());
            stream.flush();
         }
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true)); // Write access on an existing file
         CHECK(storage.deleteByName("Stg/b"));
         POLE::Stream added(&storage, "Stg/d", true);
         string addedContent = "new stream"s;
         CHECK(added.write(reinterpret_cast<unsigned char *>(addedContent.data()), addedContent.size()) == addedContent.size());
         POLE::Stream rewritten(&storage, "Stg/a");
         string rewrittenContent = "rewritten, longer than before"s;
         rewritten.setSize(0);
         rewritten.seek(0);
         CHECK(rewritten.write(reinterpret_cast<unsigned char *>(rewrittenContent.data()), rewrittenContent.size()) == rewrittenContent.size());
         rewritten.flush();
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK_FALSE(storage.exists("Stg/b"));
         CHECK(ReadPoleStream(storage, "Stg/a") == ToBytes("rewritten, longer than before"s));
         CHECK(ReadPoleStream(storage, "Stg/c") == ToBytes("content of c"s));
         CHECK(ReadPoleStream(storage, "Stg/d") == ToBytes("new stream"s));
         storage.close();
      }
   }

   SUBCASE("large number of streams (directory tree balancing)")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-many.vpx";
      std::filesystem::remove(file, ec);

      constexpr int count = 200;
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true));
         for (int i = 0; i < count; ++i)
         {
            POLE::Stream stream(&storage, std::format("Stg/s{:04}", i), true);
            string content = std::format("stream {}", i);
            CHECK(stream.write(reinterpret_cast<unsigned char *>(content.data()), content.size()) == content.size());
         }
         // Flush once all streams are written (flushes the storage header, allocation tables and directory tree)
         POLE::Stream last(&storage, "Stg/zzzz", true);
         CHECK(last.write(reinterpret_cast<unsigned char *>(const_cast<char *>("x")), 1) == 1);
         last.flush();
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK(GetStreamSet(storage).size() == count + 1);
         for (int i = 0; i < count; i += 37)
            CHECK(ReadPoleStream(storage, std::format("Stg/s{:04}", i)) == ToBytes(std::format("stream {}", i)));
         storage.close();
      }
   }
}


TEST_CASE("POLE storage conforms to the OLE format")
{
   std::error_code ec;
   string payload = "OLE structured storage payload"s;

   SUBCASE("POLE written file is readable by the native API")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-native-read.vpx";
      std::filesystem::remove(file, ec);

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true)); // 4K sectors, as produced by PinTable::Save
         POLE::Stream stream(&storage, "GameStg/GameData", true);
         CHECK(stream.write(reinterpret_cast<unsigned char *>(payload.data()), payload.size()) == payload.size());
         stream.flush();
         storage.close();
      }

      CHECK(NativeReadStream(file, L"GameStg", L"GameData") == ToBytes(payload));

      // The directory tree must also be browsable by the native API
      CComPtr<IStorage> root;
      REQUIRE(SUCCEEDED(StgOpenStorageEx(file.wstring().c_str(), STGM_READ | STGM_SHARE_DENY_WRITE, STGFMT_STORAGE, 0, nullptr, nullptr, IID_IStorage, reinterpret_cast<void **>(&root))));
      CHECK(NativeStorageEntries(root) == std::set<wstring> { L"GameStg"s });
      CComPtr<IStorage> sub;
      REQUIRE(SUCCEEDED(root->OpenStorage(L"GameStg", nullptr, STGM_READ | STGM_SHARE_EXCLUSIVE, nullptr, 0, &sub)));
      CHECK(NativeStorageEntries(sub) == std::set<wstring> { L"GameData"s });
   }

   SUBCASE("natively written file is readable by POLE")
   {
      const std::filesystem::path file = GetTmpDir() / "native-pole-read.vpx";
      std::filesystem::remove(file, ec);

      {
         CComPtr<IStorage> root;
         REQUIRE(SUCCEEDED(StgCreateDocfile(file.wstring().c_str(), STGM_CREATE | STGM_READWRITE | STGM_SHARE_EXCLUSIVE, 0, &root)));
         CComPtr<IStorage> sub;
         REQUIRE(SUCCEEDED(root->CreateStorage(L"GameStg", STGM_CREATE | STGM_READWRITE | STGM_SHARE_EXCLUSIVE, 0, 0, &sub)));
         CComPtr<IStream> stream;
         REQUIRE(SUCCEEDED(sub->CreateStream(L"GameData", STGM_CREATE | STGM_READWRITE | STGM_SHARE_EXCLUSIVE, 0, 0, &stream)));
         ULONG written = 0;
         CHECK(SUCCEEDED(stream->Write(payload.data(), static_cast<ULONG>(payload.size()), &written)));
      } // Releasing the streams and storages flushes the file to disk

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK(storage.result() == POLE::Storage::Ok);
         CHECK(ReadPoleStream(storage, "GameStg/GameData") == ToBytes(payload));
         storage.close();
      }
   }
}


TEST_CASE("BIFF reader/writer round-trip")
{
   InMemStream stream;
   const vec3 v3 = { 1.f, 2.f, 3.f };
   const uint8_t rawData[] = { 9, 8, 7, 6, 5 };
   {
      BiffWriter writer(&stream, 0);
      writer.WriteBool(FID(BOOL), true);
      writer.WriteInt(FID(INTG), -42);
      writer.WriteUInt(FID(UINT), 0xDEADBEEFu);
      writer.WriteFloat(FID(FLOT), 1.25f);
      writer.WriteString(FID(STRG), "biff string"s);
      writer.WriteWideString(FID(WSTR), L"wide string");
      writer.WriteVector3(FID(VEC3), v3);
      writer.WriteRaw(FID(RAWD), rawData, sizeof(rawData));
      writer.BeginObject(FID(SUBO), true, true); // Skippable sub object, as used e.g. for render probes in GameData
      writer.WriteInt(FID(FLD1), 7);
      writer.WriteFloat(FID(FLD2), 0.5f);
      writer.EndObject();
      writer.EndObject();
      CHECK_FALSE(writer.HasError());
   }

   bool gotBool = false;
   int gotInt = 0;
   unsigned int gotUInt = 0;
   float gotFloat = 0.f;
   string gotString;
   wstring gotWideString;
   vec3 gotV3 = {};
   vector<uint8_t> gotRaw;
   int gotSubInt = 0;
   float gotSubFloat = 0.f;

   BiffReader reader(stream.Data(), static_cast<uint32_t>(stream.Size()), CURRENT_FILE_FORMAT_VERSION, 0, 0);
   reader.AsObject(
      [&](int tag, IObjectReader &fieldReader)
      {
         switch (tag)
         {
         case FID(BOOL): gotBool = fieldReader.AsBool(); break;
         case FID(INTG): gotInt = fieldReader.AsInt(); break;
         case FID(UINT): gotUInt = fieldReader.AsUInt(); break;
         case FID(FLOT): gotFloat = fieldReader.AsFloat(); break;
         case FID(STRG): gotString = fieldReader.AsString(); break;
         case FID(WSTR): gotWideString = fieldReader.AsWideString(); break;
         case FID(VEC3): gotV3 = fieldReader.AsVector3(); break;
         case FID(RAWD):
            gotRaw.resize(sizeof(rawData));
            fieldReader.AsRaw(gotRaw.data(), sizeof(rawData));
            break;
         case FID(SUBO):
            fieldReader.AsObject(
               [&](int subTag, IObjectReader &subReader)
               {
                  if (subTag == FID(FLD1))
                     gotSubInt = subReader.AsInt();
                  else if (subTag == FID(FLD2))
                     gotSubFloat = subReader.AsFloat();
                  return true;
               },
               true);
            break;
         default: break;
         }
         return true;
      });

   CHECK_FALSE(reader.HasError());
   CHECK(gotBool == true);
   CHECK(gotInt == -42);
   CHECK(gotUInt == 0xDEADBEEFu);
   CHECK(gotFloat == 1.25f);
   CHECK(gotString == "biff string"s);
   CHECK(gotWideString == L"wide string"s);
   CHECK(gotV3.x == 1.f);
   CHECK(gotV3.y == 2.f);
   CHECK(gotV3.z == 3.f);
   CHECK(gotRaw == vector<uint8_t>(std::begin(rawData), std::end(rawData)));
   CHECK(gotSubInt == 7);
   CHECK(gotSubFloat == 0.5f);
}


TEST_CASE("Table file save/load round-trip")
{
   std::error_code ec;
   const std::filesystem::path out1 = GetTmpDir() / "roundtrip-1.vpx";
   const std::filesystem::path out2 = GetTmpDir() / "roundtrip-2.vpx";
   std::filesystem::remove(out1, ec);
   std::filesystem::remove(out2, ec);

   CComObject<PinTable> *table;
   CComObject<PinTable>::CreateInstance(&table);
   table->AddRef();
   TestFileFeedback feedback;
   REQUIRE(SUCCEEDED(table->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", feedback)));

   table->m_filename = out1;
   CHECK(SUCCEEDED(table->Save(feedback)));
   CHECK(feedback.m_isMonotonic);
   CHECK(feedback.m_lastProgress == feedback.m_length); // Save reports the progress of every single saved item

   // The saved file must be a valid OLE container, readable by the native API
   CHECK(NativeReadStream(out1, L"GameStg", L"GameData").size() > 0);
   CHECK(NativeReadStream(out1, L"GameStg", L"MAC").size() > 0);

   CComObject<PinTable> *reloaded;
   CComObject<PinTable>::CreateInstance(&reloaded);
   reloaded->AddRef();
   TestFileFeedback feedback2;
   REQUIRE(SUCCEEDED(reloaded->LoadGameFromFilename(out1, feedback2)));
   CHECK(feedback2.m_isMonotonic);
   CHECK(feedback2.m_lastProgress <= feedback2.m_length);

   // Same scene content
   CHECK(reloaded->GetParts().size() == table->GetParts().size());
   CHECK(reloaded->GetImageList().size() == table->GetImageList().size());
   CHECK(reloaded->m_vsound.size() == table->m_vsound.size());
   CHECK(reloaded->GetFontList().size() == table->GetFontList().size());
   CHECK(reloaded->GetCollections().size() == table->GetCollections().size());
   CHECK(reloaded->m_vrenderprobe.size() == table->m_vrenderprobe.size());
   std::set<string> partNames, reloadedPartNames;
   for (const IEditable *part : table->GetParts())
      partNames.insert(part->GetName());
   for (const IEditable *part : reloaded->GetParts())
      reloadedPartNames.insert(part->GetName());
   CHECK(reloadedPartNames == partNames);

   reloaded->m_filename = out2;
   CHECK(SUCCEEDED(reloaded->Save(feedback2)));

   // The two generated files must be byte-identical, except volatile TableInfo fields
   // (GameStg/MAC is compared: it is a hash over all the non volatile content, so any
   // silent difference in the round-tripped data makes it fail)
   CompareStorageFiles(out1, out2, { "TableInfo/TableSaveDate", "TableInfo/TableSaveRev" });

   reloaded->Release();
   table->Release();
}
