// license:GPLv3+

#include "ui/VPXFileFeedback.h"
#include "utils/fileio.h"

class IEditable;
class PinTable;

extern std::filesystem::path GetAssetPath();
extern bool CheckMatchingBitmaps(const string& filePath1, const string& filePath2);
extern void CaptureRender(const string& tablePath, const string& screenshotPath);

extern void ResetVPX();

// Creates an empty table to own test parts. Call Release() when done (parts
// added through AddPart are released with it).
PinTable* CreateTestTable();

// Serializes a part to an in-memory BIFF stream, in the same format used for
// the "GameStg/GameItemN" streams of a .vpx file.
InMemStream SavePartToStream(IEditable* part);

// Loads a part from a stream produced by SavePartToStream. `part` must be a
// freshly created object (e.g. T::COMCreate()), matching the file loading path
// (no prior Init call, Load applies defaults then reads the fields).
void LoadPartFromStream(IEditable* part, const InMemStream& stream);

// Byte-compares two in-memory streams.
bool StreamsEqual(const InMemStream& a, const InMemStream& b);

// Temp folder for files generated by the tests (under the build output's test-assets).
std::filesystem::path GetTestTmpDir();

// Records the progress reported while loading or saving a table, so tests can verify
// that it grows monotonically and reaches the announced total length.
class TestFileFeedback final : public VPXFileFeedback
{
public:
   void SetProgress(unsigned int progress) override
   {
      m_isMonotonic &= (m_progressCalls == 0) || (progress >= m_lastProgress);
      m_lastProgress = progress;
      ++m_progressCalls;
   }
   void SetLength(unsigned int length) override
   {
      // Each reported operation starts with SetLength: reset the recorded progress
      m_length = length;
      m_lastProgress = 0;
      m_progressCalls = 0;
      m_isMonotonic = true;
   }

   unsigned int m_length = 0;
   unsigned int m_lastProgress = 0;
   unsigned int m_progressCalls = 0;
   bool m_isMonotonic = true;
};

#ifdef ENABLE_BGFX
bgfx::RendererType::Enum GetLastRenderer();
#endif
