#!/bin/bash

WINE_SRC="/Users/jmillard/wine-41abefccebf2729a70be9ec7bdb1c6226a56e369"
WINE_VPX="/Users/jmillard/vpinball/standalone/inc/wine"

find $WINE_VPX -type f | while read i; do
  if [[ "$i" == *".DS_Store" ]]; then
     continue
  fi

  RELATIVE_PATH=${i#$WINE_VPX/}

  if [ "$RELATIVE_PATH" != "dlls/vbscript/parser.tab.c" ] &&
     [ "$RELATIVE_PATH" != "dlls/vbscript/parser.tab.h" ]; then
        FILE="$WINE_SRC/$RELATIVE_PATH"
        if [ -f "$FILE" ]; then
            touch "$i"
            PATCH=$(diff -w -u "$FILE" "$i")
            if [ ! -z "$PATCH" ]; then
               echo "$PATCH"
            fi
        fi
  fi
done
