// license:GPLv3+

#include "core/stdafx.h"
#include "../vpx-test.h"

#include "core/VPApp.h"
#include "math/Mesh.h"
#include "parts/Material.h"
#include "parts/PartGroup.h"
#include "parts/pintable.h"
#include "parts/surface.h"
#include "renderer/RenderProbe.h"
#include "utils/fileio.h"
#include "utils/BiffReader.h"
#include "utils/BiffWriter.h"
#include "utils/JSONSerializer.h"

#include <nlohmann/json.hpp>

#include "pole/pole.h"

#include "doctest.h"

#ifndef __STANDALONE__
#include <objbase.h>
#endif
#include <filesystem>
#include <fstream>
#include <set>

// Temp folder for files generated by the tests (under the build output's test-assets)
static std::filesystem::path GetTmpDir()
{
   const std::filesystem::path dir = GetAssetPath() / "tmp";
   std::filesystem::create_directories(dir);
   return dir;
}

static vector<uint8_t> ToBytes(const string &str) { return vector<uint8_t>(str.begin(), str.end()); }

// Reads an entire POLE stream, checks the stream exists and could be fully read
static vector<uint8_t> ReadPoleStream(POLE::Storage &storage, const string &name)
{
   POLE::Stream stream(&storage, name);
   REQUIRE(!stream.fail());
   vector<uint8_t> data(static_cast<size_t>(stream.size()));
   if (!data.empty())
      CHECK(stream.read(data.data(), static_cast<uint64_t>(data.size())) == data.size());
   return data;
}

// Returns the full path of every stream in the storage (e.g. "GameStg/GameData")
static std::set<string> GetStreamSet(POLE::Storage &storage)
{
   std::set<string> result;
   for (const string &name : storage.GetAllStreams("/"))
      result.insert(!name.empty() && name[0] == '/' ? name.substr(1) : name);
   return result;
}

// Byte-compares every stream of two OLE container files, except the listed volatile streams
static void CompareStorageFiles(const std::filesystem::path &fileA, const std::filesystem::path &fileB, const std::initializer_list<string> &volatileStreams)
{
   POLE::Storage storageA(fileA.string().c_str());
   POLE::Storage storageB(fileB.string().c_str());
   REQUIRE(storageA.open());
   REQUIRE(storageB.open());
   const std::set<string> streamsA = GetStreamSet(storageA);
   CHECK(streamsA == GetStreamSet(storageB));
   for (const string &name : streamsA)
   {
      if (std::find(volatileStreams.begin(), volatileStreams.end(), name) != volatileStreams.end())
         continue;
      INFO("Comparing stream '", name, "'");
      CHECK(ReadPoleStream(storageA, name) == ReadPoleStream(storageB, name));
   }
   storageA.close();
   storageB.close();
}

// Reads a stream from an OLE container using the Windows native structured storage API.
// This is an oracle validating that files written by POLE conform to the OLE format
// (and therefore remain readable by older VPX versions and third-party tools).
// Only available on the Win32 build: standalone builds have no native OLE structured storage.
#ifndef __STANDALONE__
static vector<uint8_t> NativeReadStream(const std::filesystem::path &file, const wchar_t *storageName, const wchar_t *streamName)
{
   vector<uint8_t> result;
   CComPtr<IStorage> root;
   if (FAILED(StgOpenStorageEx(file.wstring().c_str(), STGM_READ | STGM_SHARE_DENY_WRITE, STGFMT_STORAGE, 0, nullptr, nullptr, IID_IStorage, reinterpret_cast<void **>(&root))))
      return result;
   CComPtr<IStorage> sub;
   if (FAILED(root->OpenStorage(storageName, nullptr, STGM_READ | STGM_SHARE_EXCLUSIVE, nullptr, 0, &sub)))
      return result;
   CComPtr<IStream> stream;
   if (FAILED(sub->OpenStream(streamName, nullptr, STGM_READ | STGM_SHARE_EXCLUSIVE, 0, &stream)))
      return result;
   STATSTG stat;
   if (FAILED(stream->Stat(&stat, STATFLAG_NONAME)))
      return result;
   result.resize(static_cast<size_t>(stat.cbSize.QuadPart));
   ULONG bytesRead = 0;
   if (!result.empty() && (FAILED(stream->Read(result.data(), static_cast<ULONG>(result.size()), &bytesRead)) || bytesRead != result.size()))
      result.clear();
   return result;
}

// Enumerates the entry names of a native structured storage
static std::set<wstring> NativeStorageEntries(IStorage *storage)
{
   std::set<wstring> names;
   CComPtr<IEnumSTATSTG> enumerator;
   if (FAILED(storage->EnumElements(0, nullptr, 0, &enumerator)))
      return names;
   STATSTG stat;
   while (enumerator->Next(1, &stat, nullptr) == S_OK)
   {
      names.insert(stat.pwcsName);
      CoTaskMemFree(stat.pwcsName);
   }
   return names;
}
#endif // !__STANDALONE__


TEST_CASE("POLE structured storage")
{
   std::error_code ec;

   SUBCASE("round-trip of small, large and nested streams")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-basic.vpx";
      std::filesystem::remove(file, ec);

      vector<uint8_t> big(64 * 1024); // Large stream, stored in the regular FAT
      for (size_t i = 0; i < big.size(); ++i)
         big[i] = static_cast<uint8_t>(i * 31 + 17);
      string smallStr = "Small stream, stored in the mini FAT"s;

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true)); // Write access, create, 4K sectors (as used by PinTable::Save)
         POLE::Stream bigStream(&storage, "GameStg/GameData", true);
         CHECK(bigStream.write(big.data(), big.size()) == big.size());
         POLE::Stream smallStream(&storage, "TableInfo/TableName", true);
         CHECK(smallStream.write(reinterpret_cast<unsigned char *>(smallStr.data()), smallStr.size()) == smallStr.size());
         bigStream.flush(); // Flushes the storage header, allocation tables and directory tree
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK(storage.result() == POLE::Storage::Ok);
         CHECK(storage.isDirectory("GameStg"));
         CHECK(ReadPoleStream(storage, "GameStg/GameData") == big);
         CHECK(ReadPoleStream(storage, "TableInfo/TableName") == ToBytes(smallStr));
         CHECK(GetStreamSet(storage) == std::set<string> { "GameStg/GameData"s, "TableInfo/TableName"s });
         storage.close();
      }
   }

   SUBCASE("round-trip through a non ASCII path")
   {
      // Includes a non Latin-1 character, not representable in most ANSI code pages
      const std::filesystem::path file = GetTmpDir() / std::filesystem::path(u8"pole-\u00e9t\u00e9-\u8868.vpx");
      std::filesystem::remove(file, ec);
      string str = "Stream in a table with a non ASCII path"s;
      {
         POLE::Storage storage(POLE::PathToFilename(file).c_str());
         REQUIRE(storage.open(true, true, true));
         POLE::Stream stream(&storage, "TableInfo/TableName", true);
         CHECK(stream.write(reinterpret_cast<unsigned char *>(str.data()), str.size()) == str.size());
         stream.flush();
         storage.close();
         CHECK(!storage.hasWriteError());
      }
      CHECK(std::filesystem::exists(file));
      {
         POLE::Storage storage(POLE::PathToFilename(file).c_str());
         REQUIRE(storage.open());
         CHECK(ReadPoleStream(storage, "TableInfo/TableName") == ToBytes(str));
         storage.close();
      }
      std::filesystem::remove(file, ec);
   }

   SUBCASE("corrupted files are rejected without crashing")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-corrupt.vpx";
      std::filesystem::remove(file, ec);
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true));
         POLE::Stream stream(&storage, "GameStg/GameData", true);
         vector<uint8_t> data(16 * 1024, 0x55);
         CHECK(stream.write(data.data(), data.size()) == data.size());
         stream.flush();
         storage.close();
      }
      vector<uint8_t> bytes(std::filesystem::file_size(file));
      {
         std::ifstream in(file, std::ios::binary);
         in.read(reinterpret_cast<char *>(bytes.data()), bytes.size());
      }
      const auto writeFile = [&file](const vector<uint8_t> &content)
      {
         std::ofstream out(file, std::ios::binary | std::ios::trunc);
         out.write(reinterpret_cast<const char *>(content.data()), content.size());
      };

      // FAT sector count far larger than the file (would request a huge allocation)
      {
         vector<uint8_t> corrupt = bytes;
         corrupt[0x2C] = corrupt[0x2D] = corrupt[0x2E] = 0xFF;
         corrupt[0x2F] = 0x0F;
         writeFile(corrupt);
         POLE::Storage storage(file.string().c_str());
         CHECK(!storage.open());
         CHECK(storage.result() == POLE::Storage::BadOLE);
      }

      // File truncated to its header: allocation tables and directory are missing
      {
         writeFile(vector<uint8_t>(bytes.begin(), bytes.begin() + 512));
         POLE::Storage storage(file.string().c_str());
         CHECK(!storage.open());
      }
      std::filesystem::remove(file, ec);
   }

   SUBCASE("incremental update of an existing file")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-update.vpx";
      std::filesystem::remove(file, ec);

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true));
         for (const char *name : { "a", "b", "c" })
         {
            POLE::Stream stream(&storage, std::format("Stg/{}", name), true);
            string content = "content of "s + name;
            CHECK(stream.write(reinterpret_cast<unsigned char *>(content.data()), content.size()) == content.size());
            stream.flush();
         }
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true)); // Write access on an existing file
         CHECK(storage.deleteByName("Stg/b"));
         POLE::Stream added(&storage, "Stg/d", true);
         string addedContent = "new stream"s;
         CHECK(added.write(reinterpret_cast<unsigned char *>(addedContent.data()), addedContent.size()) == addedContent.size());
         POLE::Stream rewritten(&storage, "Stg/a");
         string rewrittenContent = "rewritten, longer than before"s;
         rewritten.setSize(0);
         rewritten.seek(0);
         CHECK(rewritten.write(reinterpret_cast<unsigned char *>(rewrittenContent.data()), rewrittenContent.size()) == rewrittenContent.size());
         rewritten.flush();
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK_FALSE(storage.exists("Stg/b"));
         CHECK(ReadPoleStream(storage, "Stg/a") == ToBytes("rewritten, longer than before"s));
         CHECK(ReadPoleStream(storage, "Stg/c") == ToBytes("content of c"s));
         CHECK(ReadPoleStream(storage, "Stg/d") == ToBytes("new stream"s));
         storage.close();
      }
   }

   SUBCASE("large number of streams (directory tree balancing)")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-many.vpx";
      std::filesystem::remove(file, ec);

      constexpr int count = 200;
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true));
         for (int i = 0; i < count; ++i)
         {
            POLE::Stream stream(&storage, std::format("Stg/s{:04}", i), true);
            string content = std::format("stream {}", i);
            CHECK(stream.write(reinterpret_cast<unsigned char *>(content.data()), content.size()) == content.size());
         }
         // Flush once all streams are written (flushes the storage header, allocation tables and directory tree)
         POLE::Stream last(&storage, "Stg/zzzz", true);
         CHECK(last.write(reinterpret_cast<unsigned char *>(const_cast<char *>("x")), 1) == 1);
         last.flush();
         storage.close();
      }
      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK(GetStreamSet(storage).size() == count + 1);
         for (int i = 0; i < count; i += 37)
            CHECK(ReadPoleStream(storage, std::format("Stg/s{:04}", i)) == ToBytes(std::format("stream {}", i)));
         storage.close();
      }
   }
}


#ifndef __STANDALONE__
TEST_CASE("POLE storage conforms to the OLE format")
{
   std::error_code ec;
   string payload = "OLE structured storage payload"s;

   SUBCASE("POLE written file is readable by the native API")
   {
      const std::filesystem::path file = GetTmpDir() / "pole-native-read.vpx";
      std::filesystem::remove(file, ec);

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open(true, true, true)); // 4K sectors, as produced by PinTable::Save
         POLE::Stream stream(&storage, "GameStg/GameData", true);
         CHECK(stream.write(reinterpret_cast<unsigned char *>(payload.data()), payload.size()) == payload.size());
         stream.flush();
         storage.close();
      }

      CHECK(NativeReadStream(file, L"GameStg", L"GameData") == ToBytes(payload));

      // The directory tree must also be browsable by the native API
      CComPtr<IStorage> root;
      REQUIRE(SUCCEEDED(StgOpenStorageEx(file.wstring().c_str(), STGM_READ | STGM_SHARE_DENY_WRITE, STGFMT_STORAGE, 0, nullptr, nullptr, IID_IStorage, reinterpret_cast<void **>(&root))));
      CHECK(NativeStorageEntries(root) == std::set<wstring> { L"GameStg"s });
      CComPtr<IStorage> sub;
      REQUIRE(SUCCEEDED(root->OpenStorage(L"GameStg", nullptr, STGM_READ | STGM_SHARE_EXCLUSIVE, nullptr, 0, &sub)));
      CHECK(NativeStorageEntries(sub) == std::set<wstring> { L"GameData"s });
   }

   SUBCASE("natively written file is readable by POLE")
   {
      const std::filesystem::path file = GetTmpDir() / "native-pole-read.vpx";
      std::filesystem::remove(file, ec);

      {
         CComPtr<IStorage> root;
         REQUIRE(SUCCEEDED(StgCreateDocfile(file.wstring().c_str(), STGM_CREATE | STGM_READWRITE | STGM_SHARE_EXCLUSIVE, 0, &root)));
         CComPtr<IStorage> sub;
         REQUIRE(SUCCEEDED(root->CreateStorage(L"GameStg", STGM_CREATE | STGM_READWRITE | STGM_SHARE_EXCLUSIVE, 0, 0, &sub)));
         CComPtr<IStream> stream;
         REQUIRE(SUCCEEDED(sub->CreateStream(L"GameData", STGM_CREATE | STGM_READWRITE | STGM_SHARE_EXCLUSIVE, 0, 0, &stream)));
         ULONG written = 0;
         CHECK(SUCCEEDED(stream->Write(payload.data(), static_cast<ULONG>(payload.size()), &written)));
      } // Releasing the streams and storages flushes the file to disk

      {
         POLE::Storage storage(file.string().c_str());
         REQUIRE(storage.open());
         CHECK(storage.result() == POLE::Storage::Ok);
         CHECK(ReadPoleStream(storage, "GameStg/GameData") == ToBytes(payload));
         storage.close();
      }
   }
}
#endif // !__STANDALONE__


TEST_CASE("BIFF reader/writer round-trip")
{
   InMemStream stream;
   const vec3 v3 = { 1.f, 2.f, 3.f };
   const uint8_t rawData[] = { 9, 8, 7, 6, 5 };
   {
      BiffWriter writer(&stream, 0);
      writer.WriteBool(FID(BOOL), true);
      writer.WriteInt(FID(INTG), -42);
      writer.WriteUInt(FID(UINT), 0xDEADBEEFu);
      writer.WriteFloat(FID(FLOT), 1.25f);
      writer.WriteString(FID(STRG), "biff string"s);
      writer.WriteWideString(FID(WSTR), L"wide string");
      writer.WriteVector3(FID(VEC3), v3);
      writer.WriteRaw(FID(RAWD), rawData, sizeof(rawData));
      writer.BeginObject(FID(SUBO), true, true); // Skippable sub object, as used e.g. for render probes in GameData
      writer.WriteInt(FID(FLD1), 7);
      writer.WriteFloat(FID(FLD2), 0.5f);
      writer.EndObject();
      writer.EndObject();
      CHECK_FALSE(writer.HasError());
   }

   bool gotBool = false;
   int gotInt = 0;
   unsigned int gotUInt = 0;
   float gotFloat = 0.f;
   string gotString;
   wstring gotWideString;
   vec3 gotV3 = {};
   vector<uint8_t> gotRaw;
   int gotSubInt = 0;
   float gotSubFloat = 0.f;

   BiffReader reader(stream.Data(), static_cast<uint32_t>(stream.Size()), CURRENT_FILE_FORMAT_VERSION, 0, 0);
   reader.AsObject(
      [&](int tag, IObjectReader &fieldReader)
      {
         switch (tag)
         {
         case FID(BOOL): gotBool = fieldReader.AsBool(); break;
         case FID(INTG): gotInt = fieldReader.AsInt(); break;
         case FID(UINT): gotUInt = fieldReader.AsUInt(); break;
         case FID(FLOT): gotFloat = fieldReader.AsFloat(); break;
         case FID(STRG): gotString = fieldReader.AsString(); break;
         case FID(WSTR): gotWideString = fieldReader.AsWideString(); break;
         case FID(VEC3): gotV3 = fieldReader.AsVector3(); break;
         case FID(RAWD):
            gotRaw.resize(sizeof(rawData));
            fieldReader.AsRaw(gotRaw.data(), sizeof(rawData));
            break;
         case FID(SUBO):
            fieldReader.AsObject(
               [&](int subTag, IObjectReader &subReader)
               {
                  if (subTag == FID(FLD1))
                     gotSubInt = subReader.AsInt();
                  else if (subTag == FID(FLD2))
                     gotSubFloat = subReader.AsFloat();
                  return true;
               },
               true);
            break;
         default: break;
         }
         return true;
      });

   CHECK_FALSE(reader.HasError());
   CHECK(gotBool == true);
   CHECK(gotInt == -42);
   CHECK(gotUInt == 0xDEADBEEFu);
   CHECK(gotFloat == 1.25f);
   CHECK(gotString == "biff string"s);
   CHECK(gotWideString == L"wide string"s);
   CHECK(gotV3.x == 1.f);
   CHECK(gotV3.y == 2.f);
   CHECK(gotV3.z == 3.f);
   CHECK(gotRaw == vector<uint8_t>(std::begin(rawData), std::end(rawData)));
   CHECK(gotSubInt == 7);
   CHECK(gotSubFloat == 0.5f);
}


TEST_CASE("Table file save/load round-trip")
{
   std::error_code ec;
   const std::filesystem::path out1 = GetTmpDir() / "roundtrip-1.vpx";
   const std::filesystem::path out2 = GetTmpDir() / "roundtrip-2.vpx";
   std::filesystem::remove(out1, ec);
   std::filesystem::remove(out2, ec);

   CComObject<PinTable> *table;
   CComObject<PinTable>::CreateInstance(&table);
   table->AddRef();
   TestFileFeedback feedback;
   REQUIRE(SUCCEEDED(table->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", feedback)));

   table->m_filename = out1;
   CHECK(SUCCEEDED(table->Save(feedback)));
   CHECK(feedback.m_isMonotonic);
   CHECK(feedback.m_lastProgress == feedback.m_length); // Save reports the progress of every single saved item

#ifndef __STANDALONE__
   // The saved file must be a valid OLE container, readable by the native API
   CHECK(NativeReadStream(out1, L"GameStg", L"GameData").size() > 0);
   CHECK(NativeReadStream(out1, L"GameStg", L"MAC").size() > 0);
#endif

   CComObject<PinTable> *reloaded;
   CComObject<PinTable>::CreateInstance(&reloaded);
   reloaded->AddRef();
   TestFileFeedback feedback2;
   REQUIRE(SUCCEEDED(reloaded->LoadGameFromFilename(out1, feedback2)));
   CHECK(feedback2.m_isMonotonic);
   CHECK(feedback2.m_lastProgress <= feedback2.m_length);

   // Same scene content
   CHECK(reloaded->GetParts().size() == table->GetParts().size());
   CHECK(reloaded->GetImageList().size() == table->GetImageList().size());
   CHECK(reloaded->m_vsound.size() == table->m_vsound.size());
   CHECK(reloaded->GetFontList().size() == table->GetFontList().size());
   CHECK(reloaded->GetCollections().size() == table->GetCollections().size());
   CHECK(reloaded->m_vrenderprobe.size() == table->m_vrenderprobe.size());
   std::set<string> partNames, reloadedPartNames;
   for (const IEditable *part : table->GetParts())
      partNames.insert(part->GetName());
   for (const IEditable *part : reloaded->GetParts())
      reloadedPartNames.insert(part->GetName());
   CHECK(reloadedPartNames == partNames);

   reloaded->m_filename = out2;
   CHECK(SUCCEEDED(reloaded->Save(feedback2)));

   // The two generated files must be byte-identical, except volatile TableInfo fields
   // (GameStg/MAC is compared: it is a hash over all the non volatile content, so any
   // silent difference in the round-tripped data makes it fail)
   CompareStorageFiles(out1, out2, { "TableInfo/TableSaveDate", "TableInfo/TableSaveRev" });

   reloaded->Release();
   table->Release();
}


// Checks that a table reloaded from a VPZ pack has the same content as the original table
static void CheckSameTableContent(const PinTable *table, const PinTable *reloaded)
{
   CHECK(reloaded->GetParts().size() == table->GetParts().size());
   CHECK(reloaded->GetImageList().size() == table->GetImageList().size());
   CHECK(reloaded->m_vsound.size() == table->m_vsound.size());
   for (size_t i = 0; i < table->m_vsound.size(); ++i)
   {
      CHECK(reloaded->m_vsound[i]->GetName() == table->m_vsound[i]->GetName());
      CHECK(reloaded->m_vsound[i]->GetFrontRearFade() == table->m_vsound[i]->GetFrontRearFade());
   }
   CHECK(reloaded->GetFontList().size() == table->GetFontList().size());
   CHECK(reloaded->GetCollections().size() == table->GetCollections().size());
   CHECK(reloaded->m_vrenderprobe.size() == table->m_vrenderprobe.size());
   CHECK(reloaded->m_materials.size() == table->m_materials.size());
   std::set<string> materialNames, reloadedMaterialNames;
   for (const Material *material : table->m_materials)
      materialNames.insert(material->m_name);
   for (const Material *material : reloaded->m_materials)
      reloadedMaterialNames.insert(material->m_name);
   CHECK(reloadedMaterialNames == materialNames);
   std::set<string> partNames, reloadedPartNames;
   for (const IEditable *part : table->GetParts())
      partNames.insert(part->GetName());
   for (const IEditable *part : reloaded->GetParts())
      reloadedPartNames.insert(part->GetName());
   CHECK(reloadedPartNames == partNames);
   CHECK(reloaded->m_tableName == table->m_tableName);
   CHECK(reloaded->m_script_text == table->m_script_text);
   CHECK(reloaded->m_customInfo == table->m_customInfo);
}


TEST_CASE("VPZ pack save/load round-trip")
{
   std::error_code ec;

   CComObject<PinTable> *table;
   CComObject<PinTable>::CreateInstance(&table);
   table->AddRef();
   TestFileFeedback feedback;
   REQUIRE(SUCCEEDED(table->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", feedback)));

   // Add a render probe and a sound so that the pack layout holds them (default tables have none)
   RenderProbe *const probe = table->NewRenderProbe();
   probe->SetName("test_probe");
   vector<uint8_t> soundData = { 'I', 'D', '3', 0 };
   VPX::Sound *const sound = new VPX::Sound("test_sound", "imported.mp3"s, soundData);
   sound->SetFrontRearFade(-75); // -100 is full rear, +100 is full front
   table->m_vsound.push_back(sound);

   SUBCASE("folder pack")
   {
      // A pack folder uses the same .vpz extension as the zip archive
      const std::filesystem::path packPath = GetTmpDir() / "roundtrip.vpz";
      std::filesystem::remove_all(packPath, ec);
      REQUIRE(std::filesystem::create_directories(packPath, ec));

      TestFileFeedback saveFeedback;
      CHECK(SUCCEEDED(table->SaveToJSON(packPath, saveFeedback)));
      CHECK(saveFeedback.m_isMonotonic);

      CHECK(std::filesystem::exists(packPath / "manifest.json"));
      CHECK(std::filesystem::exists(packPath / "table.json"));
      CHECK(std::filesystem::exists(packPath / "script.vbs"));
      CHECK(std::filesystem::is_directory(packPath / "parts"));

      // The manifest identifies the pack format (which may also hold partial data, hence "vpinball-pack")
      const nlohmann::ordered_json manifest = nlohmann::ordered_json::parse(std::ifstream(packPath / "manifest.json"));
      CHECK(manifest["$type"].get<string>() == "manifest");
      CHECK(manifest["file_format"].get<string>() == "vpinball-pack");
      CHECK(manifest["file_version"].get<int>() == 1);
      CHECK(!manifest.contains("content"));
      // Every document starts with its "$type" property
      CHECK(manifest.begin().key() == "$type");

      // Pack layout: table.json holds ordered name lists, assets are files named after their unique name
      const nlohmann::ordered_json tableDoc = nlohmann::ordered_json::parse(std::ifstream(packPath / "table.json"));
      CHECK(tableDoc.begin().key() == "$type");
      CHECK(tableDoc.value("parts", nlohmann::json()).is_array());
      CHECK(tableDoc.value("collections", nlohmann::json()).is_array());
      CHECK(tableDoc.value("materials", nlohmann::json()).is_array());
      CHECK(tableDoc.value("desktop_view", nlohmann::json()).is_object());
      CHECK(tableDoc.value("cabinet_view", nlohmann::json()).is_object());
      CHECK(tableDoc.contains("is_fullsinglescreen_view_enabled"));
      CHECK(!tableDoc.contains("part_files"));
      CHECK(!tableDoc.contains("collection_files"));
      CHECK(!tableDoc.contains("part_count"));
      CHECK(!tableDoc.contains("materials_legacy_count"));
      REQUIRE(!tableDoc["parts"].empty());
      const nlohmann::ordered_json partDoc = nlohmann::ordered_json::parse(std::ifstream(packPath / "parts" / (tableDoc["parts"][0].get<string>() + ".json")));
      CHECK(!partDoc.contains("name")); // The name is the file name
      CHECK(partDoc["$type"].is_string());
      CHECK(partDoc.begin().key() == "$type");
      // Render probes are saved as asset files of the pack (in renderprobes/), table.json keeps the name list
      CHECK(tableDoc.value("renderprobes", nlohmann::json()).is_array());
      REQUIRE(std::ranges::find_if(tableDoc["renderprobes"], [](const nlohmann::json &item) { return item.is_string() && item.get<string>() == "test_probe"s; })
         != tableDoc["renderprobes"].end());
      const nlohmann::ordered_json probeDoc = nlohmann::ordered_json::parse(std::ifstream(packPath / "renderprobes" / "test_probe.json"));
      CHECK(!probeDoc.contains("name"));
      CHECK(probeDoc["$type"].get<string>() == "renderprobe");
      CHECK(probeDoc.begin().key() == "$type");
      // Sounds: offsets follow the same naming order as left_right (-1 rear, +1 front)
      const nlohmann::ordered_json soundDoc = nlohmann::ordered_json::parse(std::ifstream(packPath / "sounds" / "test_sound.json"));
      CHECK(soundDoc.begin().key() == "$type");
      CHECK(soundDoc["$type"].get<string>() == "sound");
      CHECK(!soundDoc.contains("front_rear_offset"));
      CHECK(soundDoc["rear_front_offset"].get<int>() == -75);
      // Fields are canonically ordered (field map declaration order) for stable diffs
      {
         static const char *viewOrder[] = { "mode", "rotation", "inclination", "layback", "fov", "view_x", "view_y", "view_z", "scale_x", "scale_y", "scale_z", "horizontal_ofs",
            "vertical_ofs", "window_top_z_ofs", "window_bot_z_ofs" };
         vector<string> expected;
         for (const char *key : viewOrder)
            if (tableDoc["desktop_view"].contains(key))
               expected.push_back(key);
         vector<string> actual;
         for (const auto &[key, v] : tableDoc["desktop_view"].items())
            actual.push_back(key);
         string actualStr, expectedStr;
         for (const auto &k : actual)
            actualStr += k + ',';
         for (const auto &k : expected)
            expectedStr += k + ',';
         INFO("actual: ", actualStr, " expected: ", expectedStr);
         CHECK(actual == expected);
      }
      if (!tableDoc["materials"].empty())
      {
         const nlohmann::ordered_json matDoc = nlohmann::ordered_json::parse(std::ifstream(packPath / "materials" / (tableDoc["materials"][0].get<string>() + ".json")));
         CHECK(!matDoc.contains("name"));
         CHECK(matDoc["$type"].get<string>() == "material");
         CHECK(matDoc.begin().key() == "$type");
      }

      CComObject<PinTable> *reloaded;
      CComObject<PinTable>::CreateInstance(&reloaded);
      reloaded->AddRef();
      TestFileFeedback loadFeedback;
      REQUIRE(SUCCEEDED(reloaded->LoadGameFromFilename(packPath, loadFeedback)));
      CHECK(loadFeedback.m_isMonotonic);
      CheckSameTableContent(table, reloaded);
      reloaded->Release();
      std::filesystem::remove_all(packPath, ec);
   }

   SUBCASE("zip pack")
   {
      const std::filesystem::path packPath = GetTmpDir() / "roundtrip-zip.vpz";
      std::filesystem::remove(packPath, ec);

      TestFileFeedback saveFeedback;
      CHECK(SUCCEEDED(table->SaveToJSON(packPath, saveFeedback)));
      CHECK(saveFeedback.m_isMonotonic);

      // A .vpz file is a zip archive
      {
         std::ifstream in(packPath, std::ios::binary);
         char header[2] = { 0, 0 };
         in.read(header, 2);
         CHECK(header[0] == 'P');
         CHECK(header[1] == 'K');
      }

      CComObject<PinTable> *reloaded;
      CComObject<PinTable>::CreateInstance(&reloaded);
      reloaded->AddRef();
      TestFileFeedback loadFeedback;
      REQUIRE(SUCCEEDED(reloaded->LoadGameFromFilename(packPath, loadFeedback)));
      CHECK(loadFeedback.m_isMonotonic);
      CheckSameTableContent(table, reloaded);
      reloaded->Release();
      std::filesystem::remove(packPath, ec);
   }

   SUBCASE("pack without a table.json loads as a partial pack")
   {
      const std::filesystem::path packPath = GetTmpDir() / "partial.vpz";
      std::filesystem::remove_all(packPath, ec);
      REQUIRE(std::filesystem::create_directories(packPath, ec));
      REQUIRE(SUCCEEDED(table->SaveToJSON(packPath, feedback)));
      REQUIRE(std::filesystem::remove(packPath / "table.json", ec));

      CComObject<PinTable> *reloaded;
      CComObject<PinTable>::CreateInstance(&reloaded);
      reloaded->AddRef();
      TestFileFeedback loadFeedback;
      REQUIRE(SUCCEEDED(reloaded->LoadGameFromFilename(packPath, loadFeedback)));
      // Parts of the pack are still loaded, into a default table
      CHECK(reloaded->GetParts().size() == table->GetParts().size());
      reloaded->Release();
      std::filesystem::remove_all(packPath, ec);
   }

   SUBCASE("invalid packs are rejected")
   {
      // Folder without a manifest is not a valid pack
      const std::filesystem::path noManifest = GetTmpDir() / "no-manifest.vpz";
      std::filesystem::remove_all(noManifest, ec);
      REQUIRE(std::filesystem::create_directories(noManifest / "parts", ec));
      {
         CComObject<PinTable> *reloaded;
         CComObject<PinTable>::CreateInstance(&reloaded);
         reloaded->AddRef();
         TestFileFeedback loadFeedback;
         CHECK(FAILED(reloaded->LoadGameFromFilename(noManifest, loadFeedback)));
         reloaded->Release();
      }
      std::filesystem::remove_all(noManifest, ec);

      // Invalid manifest JSON
      const std::filesystem::path badManifest = GetTmpDir() / "bad-manifest.vpz";
      std::filesystem::remove_all(badManifest, ec);
      REQUIRE(std::filesystem::create_directories(badManifest, ec));
      {
         std::ofstream out(badManifest / "manifest.json", std::ios::binary);
         out << "{ not json";
      }
      {
         CComObject<PinTable> *reloaded;
         CComObject<PinTable>::CreateInstance(&reloaded);
         reloaded->AddRef();
         TestFileFeedback loadFeedback;
         CHECK(FAILED(reloaded->LoadGameFromFilename(badManifest, loadFeedback)));
         reloaded->Release();
      }
      // Manifest of a different format
      {
         std::ofstream out(badManifest / "manifest.json", std::ios::binary);
         out << "{ \"file_format\": \"something-else\", \"file_version\": 1 }";
      }
      {
         CComObject<PinTable> *reloaded;
         CComObject<PinTable>::CreateInstance(&reloaded);
         reloaded->AddRef();
         TestFileFeedback loadFeedback;
         CHECK(FAILED(reloaded->LoadGameFromFilename(badManifest, loadFeedback)));
         reloaded->Release();
      }
      std::filesystem::remove_all(badManifest, ec);
   }

   SUBCASE("PinTable::Save selects the writer from the filename")
   {
      // The live editor always goes through PinTable::Save, which must write a VPZ pack
      // when the filename is a pack (a directory or a .vpz file), a VPX file otherwise
      const std::filesystem::path zipPath = GetTmpDir() / "dispatch.vpz";
      std::filesystem::remove(zipPath, ec);
      table->m_filename = zipPath;
      TestFileFeedback saveFeedback;
      CHECK(SUCCEEDED(table->Save(saveFeedback)));
      {
         std::ifstream in(zipPath, std::ios::binary);
         char header[2] = { 0, 0 };
         in.read(header, 2);
         CHECK(header[0] == 'P'); // A .vpz file is a zip archive
         CHECK(header[1] == 'K');
      }
      std::filesystem::remove(zipPath, ec);

      const std::filesystem::path folderPath = GetTmpDir() / "dispatch-folder";
      std::filesystem::remove_all(folderPath, ec);
      REQUIRE(std::filesystem::create_directories(folderPath, ec));
      table->m_filename = folderPath;
      CHECK(SUCCEEDED(table->Save(saveFeedback)));
      CHECK(std::filesystem::exists(folderPath / "manifest.json"));
      CHECK(std::filesystem::exists(folderPath / "table.json"));
      std::filesystem::remove_all(folderPath, ec);

      const std::filesystem::path vpxPath = GetTmpDir() / "dispatch.vpx";
      std::filesystem::remove(vpxPath, ec);
      table->m_filename = vpxPath;
      CHECK(SUCCEEDED(table->Save(saveFeedback)));
      {
         std::ifstream in(vpxPath, std::ios::binary);
         char header[2] = { 0, 0 };
         in.read(header, 2);
         CHECK(header[0] == char(0xD0)); // A .vpx file is an OLE container
         CHECK(header[1] == char(0xCF));
      }
      std::filesystem::remove(vpxPath, ec);
   }

   table->Release();
}


TEST_CASE("VPZ partial pack export and import")
{
   std::error_code ec;

   CComObject<PinTable> *table;
   CComObject<PinTable>::CreateInstance(&table);
   table->AddRef();
   TestFileFeedback feedback;
   REQUIRE(SUCCEEDED(table->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", feedback)));

   // An unreferenced asset must not be exported with a part selection
   vector<uint8_t> soundData = { 'I', 'D', '3', 0 };
   table->m_vsound.push_back(new VPX::Sound("unreferenced_sound", "imported.mp3"s, soundData));

   SUBCASE("a partial pack holds only the selected parts and the referenced assets")
   {
      // Export to a folder pack so the produced layout can be checked
      const std::filesystem::path packPath = GetTmpDir() / "part-export.vpz";
      std::filesystem::remove_all(packPath, ec);
      REQUIRE(std::filesystem::create_directories(packPath, ec));
      vector<IEditable *> selection;
      for (IEditable *const part : table->GetParts())
         if (part->GetItemType() != eItemPartGroup && part->GetItemType() != eItemDragPoint && selection.size() < 2)
            selection.push_back(part);
      REQUIRE(selection.size() == 2);
      // The exported parts are the selection plus its part group ancestors
      std::set<IEditable *> expected(selection.begin(), selection.end());
      for (IEditable *const part : selection)
         for (PartGroup *group = part->GetPartGroup(); group != nullptr; group = group->GetPartGroup())
            expected.insert(group);

      TestFileFeedback saveFeedback;
      CHECK(SUCCEEDED(table->SavePartsToJSONPack(packPath, selection, saveFeedback)));

      // A partial pack has a manifest but no table.json
      const nlohmann::ordered_json manifest = nlohmann::ordered_json::parse(std::ifstream(packPath / "manifest.json"));
      CHECK(manifest["$type"].get<string>() == "manifest");
      CHECK(manifest["file_format"].get<string>() == "vpinball-pack");
      CHECK(!std::filesystem::exists(packPath / "table.json"));

      // Only the selected parts (and their group ancestors) are exported, files are named after their unique names
      vector<std::filesystem::path> partFiles;
      for (const std::filesystem::directory_entry &entry : std::filesystem::directory_iterator(packPath / "parts"))
         partFiles.push_back(entry.path());
      CHECK(partFiles.size() == expected.size());
      for (IEditable *const part : expected)
         CHECK(std::filesystem::exists(packPath / "parts" / (JSONSerializer::SanitizeFileName(part->GetName()) + ".json")));
      // Assets not referenced by the exported parts are not included
      CHECK(!std::filesystem::exists(packPath / "sounds"));
      CHECK(!std::filesystem::exists(packPath / "renderprobes"));

      // The partial pack loads as a table holding only the exported parts
      CComObject<PinTable> *reloaded;
      CComObject<PinTable>::CreateInstance(&reloaded);
      reloaded->AddRef();
      TestFileFeedback loadFeedback;
      REQUIRE(SUCCEEDED(reloaded->LoadGameFromFilename(packPath, loadFeedback)));
      CHECK(reloaded->GetParts().size() == expected.size());
      reloaded->Release();
      std::filesystem::remove_all(packPath, ec);
   }

   SUBCASE("import merges parts and shares assets by name")
   {
      // Export all the parts of the table to a partial pack
      const std::filesystem::path packPath = GetTmpDir() / "table-export.vpz";
      std::filesystem::remove_all(packPath, ec);
      TestFileFeedback saveFeedback;
      CHECK(SUCCEEDED(table->SavePartsToJSONPack(packPath, table->GetParts(), saveFeedback)));
      CComObject<PinTable> *pack;
      CComObject<PinTable>::CreateInstance(&pack);
      pack->AddRef();
      TestFileFeedback loadFeedback;
      REQUIRE(SUCCEEDED(pack->LoadGameFromFilename(packPath, loadFeedback)));
      CHECK(pack->GetParts().size() == table->GetParts().size());

      // Import the pack into a copy of the same table: every part is a duplicate and gets renamed
      CComObject<PinTable> *target;
      CComObject<PinTable>::CreateInstance(&target);
      target->AddRef();
      TestFileFeedback loadFeedback2;
      REQUIRE(SUCCEEDED(target->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", loadFeedback2)));
      const size_t partCount = target->GetParts().size();
      const size_t imageCount = target->GetImageList().size();
      std::set<string> originalNames;
      for (const IEditable *part : target->GetParts())
         originalNames.insert(part->GetName());
      const vector<IEditable *> imported = target->ImportParts(pack, nullptr);
      CHECK(imported.size() == table->GetParts().size());
      CHECK(target->GetParts().size() == partCount + imported.size());
      // Imported parts are added to the table, renamed since all their names were already used
      std::set<string> importedNames;
      for (IEditable *const part : imported)
      {
         CHECK(std::ranges::find(target->GetParts(), part) != target->GetParts().end());
         CHECK(!originalNames.contains(part->GetName()));
         importedNames.insert(part->GetName());
      }
      CHECK(importedNames.size() == imported.size());
      // Same named assets are shared, not duplicated
      CHECK(target->GetImageList().size() == imageCount);

      // Importing twice adds the parts again, with unique names
      CComObject<PinTable> *pack2;
      CComObject<PinTable>::CreateInstance(&pack2);
      pack2->AddRef();
      TestFileFeedback loadFeedback3;
      REQUIRE(SUCCEEDED(pack2->LoadGameFromFilename(packPath, loadFeedback3)));
      const vector<IEditable *> imported2 = target->ImportParts(pack2, nullptr);
      CHECK(target->GetParts().size() == partCount + imported.size() + imported2.size());

      pack2->Release();
      pack->Release();
      target->Release();
      std::filesystem::remove_all(packPath, ec);
   }

   SUBCASE("import merge strategies resolve asset name conflicts")
   {
      // A target table holding assets that will conflict with the pack ones by name
      CComObject<PinTable> *target;
      CComObject<PinTable>::CreateInstance(&target);
      target->AddRef();
      TestFileFeedback targetFeedback;
      REQUIRE(SUCCEEDED(target->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", targetFeedback)));
      REQUIRE(target->GetImageList().size() >= 3);
      REQUIRE(!target->GetMaterialList().empty());
      Texture *const brick = target->GetImageList()[0];
      brick->m_name = "brick";
      Texture *const stone = target->GetImageList()[1];
      stone->m_name = "stone";
      const vector<uint8_t> stoneData(stone->GetFileRaw(), stone->GetFileRaw() + stone->GetFileSize());
      // The conflicting image of the pack reuses the bytes of another real image (so that it loads)
      const vector<uint8_t> packBrickData(target->GetImageList()[2]->GetFileRaw(), target->GetImageList()[2]->GetFileRaw() + target->GetImageList()[2]->GetFileSize());
      target->GetMaterialList()[0]->m_name = "metal";
      const size_t imageCount = target->GetImageList().size();
      const size_t materialCount = target->GetMaterialList().size();

      // A small pack folder holding a surface that references the conflicting and the equal assets
      const std::filesystem::path packPath = GetTmpDir() / "conflicts.vpz";
      std::filesystem::remove_all(packPath, ec);
      const auto writeFile = [&packPath](const std::filesystem::path &file, const string &content)
      {
         std::filesystem::create_directories((packPath / file).parent_path());
         std::ofstream(packPath / file, std::ios::binary) << content;
      };
      writeFile("manifest.json", R"({"$type":"manifest","file_format":"vpinball-pack","file_version":1,"name":"lib"})");
      writeFile("parts/libsurface.json", R"({"$type":"surface","image":"brick","side_image":"stone","top_material":"metal"})");
      const auto imageSidecar = [](const Texture *const tex)
      { return "{\"$type\":\"image\",\"alpha_test\":"s + std::to_string(tex->m_alphaTestValue * 255.f) + ",\"opaque\":"s + (tex->IsOpaque() ? "true"s : "false"s) + "}"s; };
      writeFile("images/brick.png", string(packBrickData.begin(), packBrickData.end())); // Same name, different content
      writeFile("images/brick.json", imageSidecar(brick));
      writeFile("images/stone.png", string(stoneData.begin(), stoneData.end())); // Same name and content: shared, not duplicated
      writeFile("images/stone.json", imageSidecar(stone));
      writeFile("materials/metal.json", R"({"$type":"material","roughness":12.5})");

      const auto importPack = [&packPath](PinTable *const into, const PartImportMergeStrategy strategy)
      {
         const std::unique_ptr<JSONSerializer::Deserializer> reader = into->CreateImportDeserializer(packPath, strategy);
         REQUIRE(reader != nullptr);
         CComObject<PinTable> *pack;
         CComObject<PinTable>::CreateInstance(&pack);
         pack->AddRef();
         TestFileFeedback loadFeedback;
         REQUIRE(SUCCEEDED(pack->LoadGameFromJSONPack(*reader, loadFeedback)));
         const vector<IEditable *> imported = into->ImportParts(pack, nullptr);
         pack->Release();
         REQUIRE(imported.size() == 1);
         REQUIRE(imported[0]->GetItemType() == eItemSurface);
         return static_cast<Surface *>(imported[0]);
      };

      // Default strategy: conflicting incoming assets are renamed, equal ones are shared
      Surface *const surface = importPack(target, PartImportMergeStrategy::RenameConflict);
      CHECK(surface->m_d.m_szImage == "brick_2");
      CHECK(surface->m_d.m_szSideImage == "stone");
      CHECK(surface->m_d.m_szTopMaterial == "metal_2");
      CHECK(target->GetImage("brick") == brick);
      CHECK(target->GetImage("brick_2") != nullptr);
      CHECK(target->GetImage("stone") == stone);
      CHECK(target->GetImage("stone_2") == nullptr);
      CHECK(target->GetImageList().size() == imageCount + 1);
      CHECK(!target->IsMaterialNameUnique("metal_2"));

      // A second import renames again with a fresh unique name
      Surface *const surface2 = importPack(target, PartImportMergeStrategy::RenameConflict);
      CHECK(surface2->m_d.m_szImage == "brick_3");
      CHECK(surface2->m_d.m_szSideImage == "stone");
      CHECK(target->GetImage("brick_3") != nullptr);

      // Alternate strategy: on a name conflict the imported part reuses the existing asset
      CComObject<PinTable> *target2;
      CComObject<PinTable>::CreateInstance(&target2);
      target2->AddRef();
      TestFileFeedback targetFeedback2;
      REQUIRE(SUCCEEDED(target2->LoadGameFromFilename(GetAssetPath() / "test000-default-table.vpx", targetFeedback2)));
      target2->GetImageList()[0]->m_name = "brick";
      target2->GetImageList()[1]->m_name = "stone";
      target2->GetMaterialList()[0]->m_name = "metal";
      const size_t imageCount2 = target2->GetImageList().size();
      const size_t materialCount2 = target2->GetMaterialList().size();
      Surface *const surface3 = importPack(target2, PartImportMergeStrategy::ExistingWins);
      CHECK(surface3->m_d.m_szImage == "brick");
      CHECK(surface3->m_d.m_szSideImage == "stone");
      CHECK(surface3->m_d.m_szTopMaterial == "metal");
      CHECK(target2->GetImageList().size() == imageCount2);
      CHECK(target2->GetMaterialList().size() == materialCount2);
      target2->Release();

      target->Release();
      std::filesystem::remove_all(packPath, ec);
   }

   table->Release();
}


TEST_CASE("Mesh GLB round-trip")
{
   Mesh mesh;
   mesh.m_vertices.resize(4);
   mesh.m_vertices[0] = { 0.f, 0.f, 0.f, 0.f, 0.f, 1.f, 0.f, 0.f };
   mesh.m_vertices[1] = { 100.f, 0.f, 0.f, 0.f, 0.f, 1.f, 1.f, 0.f };
   mesh.m_vertices[2] = { 100.f, 100.f, 0.f, 0.f, 0.f, 1.f, 1.f, 1.f };
   mesh.m_vertices[3] = { 0.f, 100.f, 0.f, 0.f, 0.f, 1.f, 0.f, 1.f };
   mesh.m_indices = { 0, 1, 2, 0, 2, 3 };
   Mesh::FrameData frame;
   frame.m_frameVerts.resize(4);
   for (size_t i = 0; i < 4; ++i)
      frame.m_frameVerts[i] = { mesh.m_vertices[i].x, mesh.m_vertices[i].y, mesh.m_vertices[i].z + 10.f, 0.f, 0.f, 1.f };
   mesh.m_animationFrames.push_back(frame);

   vector<uint8_t> glb;
   REQUIRE(mesh.SaveGLB(glb));

   Mesh loaded;
   REQUIRE(loaded.LoadGLB(glb.data(), glb.size()));
   CHECK(loaded.m_vertices.size() == mesh.m_vertices.size());
   CHECK(loaded.m_indices.size() == mesh.m_indices.size());
   CHECK(loaded.m_animationFrames.size() == 1);
   for (size_t i = 0; i < mesh.m_vertices.size(); ++i)
   {
      CHECK(loaded.m_vertices[i].x == doctest::Approx(mesh.m_vertices[i].x));
      CHECK(loaded.m_vertices[i].y == doctest::Approx(mesh.m_vertices[i].y));
      CHECK(loaded.m_vertices[i].z == doctest::Approx(mesh.m_vertices[i].z));
      CHECK(loaded.m_vertices[i].tu == doctest::Approx(mesh.m_vertices[i].tu));
      CHECK(loaded.m_vertices[i].tv == doctest::Approx(mesh.m_vertices[i].tv));
   }
   for (size_t i = 0; i < mesh.m_indices.size(); ++i)
      CHECK(loaded.m_indices[i] == mesh.m_indices[i]);
   // Morph target frame restores the vertex offsets
   CHECK(loaded.m_animationFrames[0].m_frameVerts[0].z == doctest::Approx(10.f));
}


TEST_CASE("Bundled table templates pass hash validation")
{
   for (const char *file : { "blankTable.vpx", "strippedTable.vpx", "exampleTable.vpx", "lightSeqTable.vpx" })
   {
      CComObject<PinTable> *table;
      CComObject<PinTable>::CreateInstance(&table);
      table->AddRef();
      TestFileFeedback feedback;
      const std::filesystem::path filePath = g_app->m_fileLocator.GetAppPath(FileLocator::AppSubFolder::Assets, file);
      INFO("Loading bundled table '", file, "'");
      CHECK(SUCCEEDED(table->LoadGameFromFilename(filePath, feedback)));
      table->Release();
   }
}
