complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Composable']
  TooManyFunctions:
    ignoreAnnotatedFunctions: ['Preview']
  LongMethod:
    ignoreAnnotated: ['Composable']

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Za-z0-9]*'

style:
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview']
  MagicNumber:
    ignoreAnnotated: ['Composable', 'Preview']
  MaxLineLength:
    maxLineLength: 150