// license:GPLv3+

#pragma once

#include <filesystem>

#include "InputManager.h"

class SDLInputHandler final : public InputManager::InputHandler
{
public:
   explicit SDLInputHandler(InputManager& pininput)
      : m_pininput(pininput)
   {
      PLOGI << "SDL input handler registered";
      if (!SDL_InitSubSystem(SDL_INIT_JOYSTICK | SDL_INIT_GAMEPAD))
      {
         PLOGE << "Failed to initialize joystick input with error: " << SDL_GetError();
      }

      // These events are generated by the subsystem initialization (this work as long as the SDL subsystem lifecycle follows the SDLInputHandler lifecycle)
      int joystickCount = 0;
      SDL_JoystickID* const joystickIds = SDL_GetJoysticks(&joystickCount);
      for (int i = 0; i < joystickCount; i++)
         OnJoystickAdded(joystickIds[i]);
   }

   SDLInputHandler& operator=(SDLInputHandler&&) = delete;

   ~SDLInputHandler() override
   {
      for (const auto& joy : m_joysticks)
         OnJoystickRemoved(SDL_GetJoystickID(joy));
      SDL_QuitSubSystem(SDL_INIT_JOYSTICK | SDL_INIT_GAMEPAD);
   }

   void PlayRumble(const float lowFrequencySpeed, const float highFrequencySpeed, const int ms_duration) override
   {
      for (auto joy : m_joysticks)
      {
         Uint16 lowFreq = (Uint16)(saturate(lowFrequencySpeed) * 65535.0f);
         Uint16 highFreq = (Uint16)(saturate(highFrequencySpeed) * 65535.0f);
         SDL_RumbleJoystick(joy, lowFreq, highFreq, ms_duration);
      }
   }

   void Update() override
   {
      if (!SDL_JoystickEventsEnabled())
         SDL_UpdateJoysticks();
   }

   void HandleSDLEvent(const SDL_Event& e)
   {
      switch (e.type)
      {
      case SDL_EVENT_KEY_DOWN:
      case SDL_EVENT_KEY_UP:
         if (e.key.repeat == 0)
            m_pininput.PushButtonEvent(m_pininput.GetKeyboardDeviceId(), static_cast<uint16_t>(e.key.scancode), e.key.timestamp, e.key.down);
         break;

      case SDL_EVENT_MOUSE_BUTTON_DOWN:
      case SDL_EVENT_MOUSE_BUTTON_UP:
         if (e.button.which != SDL_TOUCH_MOUSEID && e.button.which != SDL_PEN_MOUSEID)
            m_pininput.PushButtonEvent(m_pininput.GetMouseDeviceId(), e.button.button, e.button.timestamp, e.button.down);
         break;

      case SDL_EVENT_JOYSTICK_ADDED: OnJoystickAdded(e.jdevice.which); break;

      case SDL_EVENT_JOYSTICK_REMOVED: OnJoystickRemoved(e.jdevice.which); break;

      case SDL_EVENT_JOYSTICK_BUTTON_DOWN:
      case SDL_EVENT_JOYSTICK_BUTTON_UP: m_pininput.PushButtonEvent(m_joystickIds[e.jbutton.which], e.jbutton.button, e.jbutton.timestamp, e.jbutton.down); break;

      case SDL_EVENT_JOYSTICK_HAT_MOTION:
      {
         const uint16_t hatId = e.jhat.hat * 4;
         m_pininput.PushButtonEvent(m_joystickIds[e.jhat.which], 0x0100 | hatId, e.jhat.timestamp, (e.jhat.value & SDL_HAT_LEFT) != 0);
         m_pininput.PushButtonEvent(m_joystickIds[e.jhat.which], 0x0101 | hatId, e.jhat.timestamp, (e.jhat.value & SDL_HAT_RIGHT) != 0);
         m_pininput.PushButtonEvent(m_joystickIds[e.jhat.which], 0x0102 | hatId, e.jhat.timestamp, (e.jhat.value & SDL_HAT_UP) != 0);
         m_pininput.PushButtonEvent(m_joystickIds[e.jhat.which], 0x0103 | hatId, e.jhat.timestamp, (e.jhat.value & SDL_HAT_DOWN) != 0);
         break;
      }

      case SDL_EVENT_JOYSTICK_AXIS_MOTION: m_pininput.PushAxisEvent(m_joystickIds[e.jaxis.which], 0x0200 | e.jaxis.axis, e.jaxis.timestamp, static_cast<float>(e.jaxis.value) / 32768.f); break;

      case SDL_EVENT_FINGER_DOWN:
      case SDL_EVENT_FINGER_UP:
         if (e.tfinger.windowID == SDL_GetWindowID(g_pplayer->m_playfieldWnd->GetCore()))
            m_pininput.PushTouchEvent(e.tfinger.x, e.tfinger.y, e.tfinger.timestamp, e.type == SDL_EVENT_FINGER_DOWN);
         break;

      default: break;
      }
   }

private:
   static string GetGamepadButtonName(SDL_Gamepad* gamepad, SDL_GamepadButton button)
   {
      switch (SDL_GetGamepadButtonLabel(gamepad, button))
      {
      case SDL_GAMEPAD_BUTTON_LABEL_A: return "A"s;
      case SDL_GAMEPAD_BUTTON_LABEL_B: return "B"s;
      case SDL_GAMEPAD_BUTTON_LABEL_X: return "X"s;
      case SDL_GAMEPAD_BUTTON_LABEL_Y: return "Y"s;
      case SDL_GAMEPAD_BUTTON_LABEL_CROSS: return "Cross"s; // ICON_FK_TIMES
      case SDL_GAMEPAD_BUTTON_LABEL_CIRCLE: return "Circle"s; // ICON_FK_CIRCLE_O
      case SDL_GAMEPAD_BUTTON_LABEL_SQUARE: return "Square"s; // ICON_FK_SQUARE_O
      case SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE: return "Triangle"s; // Sadly, nothing for triangle
      default:
         switch (button)
         {
         case SDL_GAMEPAD_BUTTON_SOUTH: return "South"s;
         case SDL_GAMEPAD_BUTTON_EAST: return "East"s;
         case SDL_GAMEPAD_BUTTON_WEST: return "West"s;
         case SDL_GAMEPAD_BUTTON_NORTH: return "North"s;
         case SDL_GAMEPAD_BUTTON_BACK: return "Back"s;
         case SDL_GAMEPAD_BUTTON_GUIDE: return "Guide"s;
         case SDL_GAMEPAD_BUTTON_START: return "Start"s;
         case SDL_GAMEPAD_BUTTON_LEFT_STICK: return "Left Stick"s;
         case SDL_GAMEPAD_BUTTON_RIGHT_STICK: return "Right Stick"s;
         case SDL_GAMEPAD_BUTTON_LEFT_SHOULDER: return "Left Shoulder"s;
         case SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER: return "Right Shoulder"s;
         case SDL_GAMEPAD_BUTTON_DPAD_UP: return "DPad Up"s;
         case SDL_GAMEPAD_BUTTON_DPAD_DOWN: return "DPad Down"s;
         case SDL_GAMEPAD_BUTTON_DPAD_LEFT: return "DPad Left"s;
         case SDL_GAMEPAD_BUTTON_DPAD_RIGHT: return "DPad Right"s;
         case SDL_GAMEPAD_BUTTON_MISC1: return "Misc #1"s;
         case SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1: return "Right Paddle 1"s;
         case SDL_GAMEPAD_BUTTON_LEFT_PADDLE1: return "Left Paddle 1"s;
         case SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2: return "Right Paddle 2"s;
         case SDL_GAMEPAD_BUTTON_LEFT_PADDLE2: return "Left Paddle 2"s;
         case SDL_GAMEPAD_BUTTON_TOUCHPAD: return "Touchpad"s;
         case SDL_GAMEPAD_BUTTON_MISC2: return "Misc #2"s;
         case SDL_GAMEPAD_BUTTON_MISC3: return "Misc #3"s;
         case SDL_GAMEPAD_BUTTON_MISC4: return "Misc #4"s;
         case SDL_GAMEPAD_BUTTON_MISC5: return "Misc #5"s;
         case SDL_GAMEPAD_BUTTON_MISC6: return "Misc #6"s;
         default: return ""s;
         }
         break;
      }
   }

   static string GetGamepadAxisName(SDL_Gamepad* gamepad, SDL_GamepadAxis axis)
   {
      switch (axis)
      {
      case SDL_GAMEPAD_AXIS_LEFTX: return "Left Stick X"s;
      case SDL_GAMEPAD_AXIS_LEFTY: return "Left Stick Y"s;
      case SDL_GAMEPAD_AXIS_RIGHTX: return "Right Stick X"s;
      case SDL_GAMEPAD_AXIS_RIGHTY: return "Right Stick Y"s;
      case SDL_GAMEPAD_AXIS_LEFT_TRIGGER: return "Left Trigger"s;
      case SDL_GAMEPAD_AXIS_RIGHT_TRIGGER: return "Right Trigger"s;
      default: return ""s;
      }
   }

   static uint16_t GetGamepadButton(SDL_GamepadButton button, SDL_GamepadBinding** bindings, int nBindings)
   {
      for (int i = 0; i < nBindings; i++)
      {
         if (bindings[i]->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON && bindings[i]->output.button == button)
         {
            if (bindings[i]->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON)
               return bindings[i]->input.button;
            else if (bindings[i]->input_type == SDL_GAMEPAD_BINDTYPE_HAT)
            {
               switch (bindings[i]->input.hat.hat_mask)
               {
               case SDL_HAT_LEFT: return 0x0100 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4);
               case SDL_HAT_RIGHT: return 0x0101 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4);
               case SDL_HAT_UP: return 0x0102 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4);
               case SDL_HAT_DOWN: return 0x0103 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4);
               }
            }
         }
      }
      return 0xFFFF;
   }

   static uint16_t GetGamepadAxis(SDL_GamepadAxis axis, SDL_GamepadBinding** bindings, int nBindings)
   {
      for (int i = 0; i < nBindings; i++)
         if (bindings[i]->input_type == SDL_GAMEPAD_BINDTYPE_AXIS && bindings[i]->output_type == SDL_GAMEPAD_BINDTYPE_AXIS && bindings[i]->output.axis.axis == axis)
            return 0x0200 | static_cast<uint16_t>(bindings[i]->input.axis.axis);
      return 0xFFFF;
   }

   static bool IsJoystickPresent(const SDL_GUID& guid)
   {
      int joystickCount = 0;
      SDL_JoystickID* const joystickIds = SDL_GetJoysticks(&joystickCount);
      for (int i = 0; i < joystickCount; i++)
      {
         if (SDL_GUID other = SDL_GetJoystickGUIDForID(joystickIds[i]); SDL_memcmp(&guid, &other, sizeof(SDL_GUID)) == 0)
            return true;
      }
      return false;
   }

   void OnJoystickAdded(SDL_JoystickID id)
   {
      auto existing = std::ranges::find_if(m_joysticks, [id](const auto& joy) { return SDL_GetJoystickID(joy) == id; });
      if (existing != m_joysticks.end())
         return; // Already present (This may happen between initial enumeration and event processing)

      SDL_Joystick* joystick = SDL_OpenJoystick(id);
      if (!joystick)
         return;

      m_joysticks.emplace_back(joystick);

      // Stable class of the device. Always available but not unique to a single device.
      // We could also use SDL_GetJoystickSerial but it does not work as a stable unique id as:
      // - it happens to not be unique as some manufacturers use a fake non unique serial number...
      // - it is not supported by all drivers, so we need a fallback anyway (for example XBox controllers)
      SDL_GUID guid = SDL_GetJoystickGUID(joystick);

      // SDL reports joystick in a stable order so we use the joystick index to distinguish between identical GUID.
      // This is not fully satisfying as in a situation with 2 identical devices, when disconnecting the first VPX will
      // wrongly identify the second as the first.
      int idIndex = 1;
      int nameIndex = 1;
      int joystickCount = 0;
      const string sdlJoyName = SDL_GetJoystickName(joystick);
      SDL_JoystickID* const joystickIds = SDL_GetJoysticks(&joystickCount);
      for (int i = 0; i < joystickCount; i++)
      {
         if (SDL_GetJoystickFromID(joystickIds[i]) == joystick)
            break;
         if (SDL_GUID other = SDL_GetJoystickGUIDForID(joystickIds[i]); SDL_memcmp(&guid, &other, sizeof(SDL_GUID)) == 0)
            idIndex++;
         if (string otherName = SDL_GetJoystickNameForID(joystickIds[i]); otherName == sdlJoyName)
            nameIndex++;
      }
      char strGuid[33];
      SDL_GUIDToString(guid, strGuid, 33);
      const string settingId = "SDLJoy_"s + strGuid + '_' + std::to_string(idIndex);

      // We used to detect and auto setup the following hardwares but this has not been readded due to hardware not being
      // available for testing and because the ingame UI allows easy setup:
      // . Microsoft's Sidewinder: date back from 1996, more or less a digital gamepad (see https://en.wikipedia.org/wiki/Microsoft_SideWinder)
      // . UltraCade's UltraPin: date back from 2000 (see https://en.wikipedia.org/wiki/UltraPin)
      // . Pinball Wizard from NanoTech: created around 2008 (see https://www.nanotechgaming.com/pinball-wizard.php)
      // . VirtuaPin: seems to be a KL25z based hardware alike Pinscape controller (see https://virtuapin.net/)
      enum
      {
         UNKNOWN,
         PINSCAPE,
         ARCADE2TV_XR_PINBALL,
         SKIP,
      } identified;
      const int nAxis = SDL_GetNumJoystickAxes(joystick);
      string joyName; // Sadly, we do not have a way to easily give a user friendly name when there are multiple devices of the same class, so we use serial number
      constexpr SDL_GUID arcade2TVGUIDs[] = { 
         { { 0x03, 0x00, 0xfa, 0x67, 0x5e, 0x04, 0x00, 0x00, 0x8e, 0x02, 0x00, 0x00, 0x02, 0x03, 0x78, 0x01 } }, // Arcade2TV-XR Dongle Arcade mode P1 (green) & Pinball mode (purple)
         { { 0x03, 0x00, 0xba, 0x66, 0x5e, 0x04, 0x00, 0x00, 0x8e, 0x02, 0x00, 0x00, 0x02, 0x03, 0x78, 0x01 } }, // Arcade2TV-XR Dongle Arcade mode P2 (green)
         { { 0x03, 0x00, 0xfa, 0x67, 0x5e, 0x04, 0x00, 0x00, 0x8e, 0x02, 0x00, 0x00, 0x40, 0x03, 0x78, 0x01 } }, // Arcade2TV-XR Wired Arcade mode P1 (green) & Pinball mode (purple)
         { { 0x03, 0x00, 0xba, 0x66, 0x5e, 0x04, 0x00, 0x00, 0x8e, 0x02, 0x00, 0x00, 0x40, 0x03, 0x78, 0x01 } }, // Arcade2TV-XR Wired Arcade mode P2 (green) & Pinball mode (purple)
      };
      if (sdlJoyName.starts_with("mjrnet Pinscape Controller"s) && nAxis >= 6)
      { // Pinscape & Pinscape Pico
         identified = PINSCAPE;
         joyName = std::format("{} #{}", sdlJoyName, nameIndex);
      }
      else if ((SDL_memcmp(&guid, &arcade2TVGUIDs[0], sizeof(guid)) == 0) || (SDL_memcmp(&guid, &arcade2TVGUIDs[2], sizeof(guid)) == 0))
      { // Arcade2TV-XR Pinball mode (purple) reported as vid: 0x045e, pid: 0x028e, that is to say 'Xbox 360 Controller (wired, standard)'
         // Sadly, Arcade mode's left stick (green) is reported with the same USB VID/PID. We just assume that the player will use the Pinball mode for pinball play
         identified = ARCADE2TV_XR_PINBALL;
         joyName = std::format("Arcade2TV-XR #{}", idIndex);
      }
      else if ((SDL_memcmp(&guid, &arcade2TVGUIDs[1], sizeof(guid)) == 0) || (SDL_memcmp(&guid, &arcade2TVGUIDs[3], sizeof(guid)) == 0))
      { // Arcade2TV-XR right stick in Arcade mode (green) but also reported (but inactive) in wired Pinball mode (purple). Just skip proposing a gamepad layout for it
         identified = SKIP;
         joyName = std::format("Arcade2TV-XR Right #{}", idIndex);
      }
      else
      {
         identified = UNKNOWN;
         joyName = std::format("{} #{}", sdlJoyName, nameIndex);
      }

      PLOGI << "Joystick connected: " << joyName.c_str() << " (SDL ID: " << id << ", Axes: " << SDL_GetNumJoystickAxes(joystick)
            << ", Buttons: " << SDL_GetNumJoystickButtons(joystick) << ", Hats: " << SDL_GetNumJoystickHats(joystick) << ", VPX UID: " << settingId.c_str() << ')';

      uint16_t deviceId = m_pininput.RegisterDevice(settingId, InputManager::DeviceType::Joystick, joyName);
      m_joystickIds[id] = deviceId;

      // Register all axis to allow selection in the UI (they will optionally be overriden if identified below)
      for (int axis = 0; axis < nAxis; axis++)
         m_pininput.RegisterElementName(deviceId, true, 0x0200 | static_cast<uint16_t>(axis), "Axis #" + std::to_string(axis));

      // If the device is recognized as a gamepad, we can get better names for buttons and axis based on the gamepad bindings
      if (SDL_Gamepad* gamepad = SDL_IsGamepad(id) ? SDL_OpenGamepad(id) : nullptr; gamepad)
      {
         int nBindings;
         if (SDL_GamepadBinding** bindings = SDL_GetGamepadBindings(gamepad, &nBindings); bindings)
         {
            for (int i = 0; i < nBindings; i++)
            {
               if (bindings[i]->input_type == SDL_GAMEPAD_BINDTYPE_BUTTON && bindings[i]->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON)
               {
                  const string name = GetGamepadButtonName(gamepad, bindings[i]->output.button);
                  if (!name.empty())
                     m_pininput.RegisterElementName(deviceId, false, static_cast<uint16_t>(bindings[i]->input.button), name);
               }
               else if (bindings[i]->input_type == SDL_GAMEPAD_BINDTYPE_HAT && bindings[i]->output_type == SDL_GAMEPAD_BINDTYPE_BUTTON)
               {
                  const string name = GetGamepadButtonName(gamepad, bindings[i]->output.button);
                  if (!name.empty())
                  {
                     switch (bindings[i]->input.hat.hat_mask)
                     {
                     case SDL_HAT_LEFT: m_pininput.RegisterElementName(deviceId, false, 0x0100 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4), name); break;
                     case SDL_HAT_RIGHT: m_pininput.RegisterElementName(deviceId, false, 0x0101 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4), name); break;
                     case SDL_HAT_UP: m_pininput.RegisterElementName(deviceId, false, 0x0102 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4), name); break;
                     case SDL_HAT_DOWN: m_pininput.RegisterElementName(deviceId, false, 0x0103 | static_cast<uint16_t>(bindings[i]->input.hat.hat * 4), name); break;
                     }
                  }
               }
               else if (bindings[i]->input_type == SDL_GAMEPAD_BINDTYPE_AXIS && bindings[i]->output_type == SDL_GAMEPAD_BINDTYPE_AXIS)
               {
                  const string name = GetGamepadAxisName(gamepad, bindings[i]->output.axis.axis);
                  if (!name.empty())
                     m_pininput.RegisterElementName(deviceId, true, 0x0200 | static_cast<uint16_t>(bindings[i]->input.axis.axis), name);
               }
            }
         }
         SDL_CloseGamepad(gamepad);
      }

      switch (identified)
      {
      case SKIP:
         // Skip the device layout proposal
         break;

      case PINSCAPE:
         // mjrnet Pinscape Controller. Obviously not a gamepad, but has defaults plunger / nudge setup layout that we can name and propose
         // We only register the 6 predefined axis. The other ports are all generic and based on user configuration
         // Note: the default mapping we propose only maps the plunger and nudge acceleration, leaving the users to decide if they want to use velocities as well (with a recent enough firmware)
         m_pininput.RegisterElementName(deviceId, true, 0x0200, "Nudge X Acceleration"s);
         m_pininput.RegisterElementName(deviceId, true, 0x0201, "Nudge Y Acceleration"s);
         m_pininput.RegisterElementName(deviceId, true, 0x0202, "Plunger Position"s);
         m_pininput.RegisterElementName(deviceId, true, 0x0203, "Nudge X Velocity"s);
         m_pininput.RegisterElementName(deviceId, true, 0x0204, "Nudge Y Velocity"s);
         m_pininput.RegisterElementName(deviceId, true, 0x0205, "Plunger Velocity"s);
         m_pininput.RegisterDefaultMapping(deviceId,
            [this, deviceId]( //
               const std::function<bool(const vector<ButtonMapping>&, unsigned int)>& mapButton, //
               const std::function<bool(const SensorMapping&, SensorMapping::Type type, bool isLinear)>& mapPlunger, //
               const std::function<bool(const SensorMapping&, const SensorMapping&)>& mapNudge)
            {
               bool success = true;
               success &= mapNudge(SensorMapping::Create(deviceId, 0x0200, SensorMapping::Type::Acceleration), SensorMapping::Create(deviceId, 0x0201, SensorMapping::Type::Acceleration));
               success &= mapPlunger(SensorMapping::Create(deviceId, 0x0202, SensorMapping::Type::Position), SensorMapping::Type::Position, true);
               return success;
            });
         break;

      case ARCADE2TV_XR_PINBALL:
         // Pinball or arcade mode => propose the default Pinball layout
         // The mapping is quite a mess with mapping overlays. Try to make it somewhat readable (buttons are labeled in this order: 1,2,3 / 4,5,6 / 7,8
         m_pininput.RegisterElementName(deviceId, true, 0x0200, "Left Stick X / Nudge X");
         m_pininput.RegisterElementName(deviceId, true, 0x0201, "Left Stick Y / Nudge Y");
         m_pininput.RegisterElementName(deviceId, true, 0x0202, "Left But. 7 / Left But. 8");
         m_pininput.RegisterElementName(deviceId, true, 0x0203, "Right Stick X");
         m_pininput.RegisterElementName(deviceId, true, 0x0204, "Right Stick Y / Plunger");
         m_pininput.RegisterElementName(deviceId, true, 0x0205, "No idea...");
         m_pininput.RegisterElementName(deviceId, false, 0x0002, "Left But. 1");
         m_pininput.RegisterElementName(deviceId, false, 0x0003, "Left But. 2");
         m_pininput.RegisterElementName(deviceId, false, 0x0004, "Left Flipper / Left But. 3");
         m_pininput.RegisterElementName(deviceId, false, 0x0000, "Left & Right But. 4");
         m_pininput.RegisterElementName(deviceId, false, 0x0001, "Left But. 5");
         m_pininput.RegisterElementName(deviceId, false, 0x0005, "Right Flipper / Left But. 6");
         m_pininput.RegisterElementName(deviceId, false, 0x0006, "Right But. 1");
         m_pininput.RegisterElementName(deviceId, false, 0x0102, "Right But. 2"); // Hat Up
         m_pininput.RegisterElementName(deviceId, false, 0x0008, "Right But. 3");
         m_pininput.RegisterElementName(deviceId, false, 0x0103, "Right But. 5"); // Hat Down
         m_pininput.RegisterElementName(deviceId, false, 0x0009, "Right But. 6");
         m_pininput.RegisterElementName(deviceId, false, 0x0100, "Right But. 7"); // Hat Left
         m_pininput.RegisterElementName(deviceId, false, 0x0101, "Right But. 8"); // Hat Right
         m_pininput.RegisterDefaultMapping(deviceId,
            [this, deviceId]( //
               const std::function<bool(const vector<ButtonMapping>&, unsigned int)>& mapButton, //
               const std::function<bool(const SensorMapping&, SensorMapping::Type type, bool isLinear)>& mapPlunger, //
               const std::function<bool(const SensorMapping&, const SensorMapping&)>& mapNudge)
            {
               bool success = true;
               success &= mapButton(ButtonMapping::Create(deviceId, 4), m_pininput.GetLeftFlipperActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 4), m_pininput.GetStagedLeftFlipperActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 5), m_pininput.GetRightFlipperActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 5), m_pininput.GetStagedRightFlipperActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 2), m_pininput.GetLeftMagnaActionId()); // Left Top row (can't use right most button due to overlay...)
               success &= mapButton(ButtonMapping::Create(deviceId, 3), m_pininput.GetAddCreditActionId(0));
               success &= mapButton(ButtonMapping::Create(deviceId, 1), m_pininput.GetVRViewUpActionId()); // Left Middle row (can't use left most & right most buttons due to overlays...)
               success &= mapButton(ButtonMapping::Create(deviceId, 0x202, -0.9f, true), m_pininput.GetVRViewCenterActionId()); // Left Bottom row
               success &= mapButton(ButtonMapping::Create(deviceId, 0x202, 0.9f), m_pininput.GetVRViewDownActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 10), m_pininput.GetStartActionId()); // 1 player button
               success &= mapButton(ButtonMapping::Create(deviceId, 7), m_pininput.GetExitGameActionId()); // 2 player button
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0102), m_pininput.GetVolumeUpActionId()); // Right Top row
               success &= mapButton(ButtonMapping::Create(deviceId, 8), m_pininput.GetRightMagnaActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0103), m_pininput.GetVolumeDownActionId()); // Right Middle row
               success &= mapButton(ButtonMapping::Create(deviceId, 9), m_pininput.GetLaunchBallActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0101), m_pininput.GetOpenInGameUIActionId()); // Right Bottom row
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0201, -0.9f, true), m_pininput.GetUIDownActionId()); // Left vertical stick
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0201, 0.9f), m_pininput.GetUIUpActionId());
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0203, -0.9f, true), m_pininput.GetUILeftActionId()); // Right horizontal stick
               success &= mapButton(ButtonMapping::Create(deviceId, 0x0203, 0.9f), m_pininput.GetUIRightActionId());
               success &= mapNudge(SensorMapping::Create(deviceId, 0x0200, SensorMapping::Type::Acceleration).WithScale(0.2f),
                  SensorMapping::Create(deviceId, 0x0201, SensorMapping::Type::Acceleration).WithScale(0.2f));
               success &= mapPlunger(SensorMapping::Create(deviceId, 0x0204, SensorMapping::Type::Position), SensorMapping::Type::Position, true);
               // The automatic setup also needs for controller view alignment
               // - ControllerCabYOffset = -22.5
               // - ControllerLockbarScale = 1.66
               // and nudge needs the filter to be enabled (8 bit accelerometer without automatic calibration)
               return success;
            });
         break;

      case UNKNOWN:
      default:
         // Propose a generic gamepad layout:
         // . Flippers: Left/Right Triggers (axis mapped as buttons with thresholds for flipper/staged flipper)
         // . Magnas: Left/Right Shoulders
         // . Coin: Y (north)
         // . Start: B (east)
         // . Launch Ball: A (south)
         // . Nudge: Left Stick
         // . Plunger: Right Stick
         // . Digital Pad: PinMAME Operator Menu
         // . Exit Interactive: Back
         // . In Game UI: Start
         if (SDL_Gamepad* gamepad = SDL_IsGamepad(id) ? SDL_OpenGamepad(id) : nullptr; gamepad)
         {
            int nBindings;
            if (SDL_GamepadBinding** bindings = SDL_GetGamepadBindings(gamepad, &nBindings); bindings)
            {
               const uint16_t leftTrigger = GetGamepadAxis(SDL_GAMEPAD_AXIS_LEFT_TRIGGER, bindings, nBindings);
               const uint16_t rightTrigger = GetGamepadAxis(SDL_GAMEPAD_AXIS_RIGHT_TRIGGER, bindings, nBindings);
               const uint16_t leftStickX = GetGamepadAxis(SDL_GAMEPAD_AXIS_LEFTX, bindings, nBindings);
               const uint16_t leftStickY = GetGamepadAxis(SDL_GAMEPAD_AXIS_LEFTY, bindings, nBindings);
               const uint16_t rightStickY = GetGamepadAxis(SDL_GAMEPAD_AXIS_RIGHTY, bindings, nBindings);
               const uint16_t leftShoulder = GetGamepadButton(SDL_GAMEPAD_BUTTON_LEFT_SHOULDER, bindings, nBindings);
               const uint16_t rightShoulder = GetGamepadButton(SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER, bindings, nBindings);
               const uint16_t southButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_SOUTH, bindings, nBindings);
               const uint16_t northButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_NORTH, bindings, nBindings);
               const uint16_t eastButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_EAST, bindings, nBindings);
               const uint16_t backButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_BACK, bindings, nBindings);
               const uint16_t startButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_START, bindings, nBindings);
               const uint16_t dpadLeftButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_DPAD_LEFT, bindings, nBindings);
               const uint16_t dpadRightButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_DPAD_RIGHT, bindings, nBindings);
               const uint16_t dpadUpButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_DPAD_UP, bindings, nBindings);
               const uint16_t dpadDownButton = GetGamepadButton(SDL_GAMEPAD_BUTTON_DPAD_DOWN, bindings, nBindings);
               if (leftTrigger != 0xFFFF && rightTrigger != 0xFFFF && leftShoulder != 0xFFFF && rightShoulder != 0xFFFF && northButton != 0xFFFF && eastButton != 0xFFFF
                  && southButton != 0xFFFF && backButton != 0xFFFF && startButton != 0xFFFF && leftStickX != 0xFFFF && leftStickY != 0xFFFF && rightStickY != 0xFFFF)
               {
                  auto defaultMapping = [this, deviceId, leftTrigger, rightTrigger, leftShoulder, rightShoulder, leftStickX, leftStickY, rightStickY, southButton, northButton, eastButton,
                                             backButton, startButton, dpadLeftButton, dpadRightButton, dpadUpButton, dpadDownButton]( //
                                             const std::function<bool(const vector<ButtonMapping>&, unsigned int)>& mapButton, //
                                             const std::function<bool(const SensorMapping&, SensorMapping::Type type, bool isLinear)>& mapPlunger, //
                                             const std::function<bool(const SensorMapping&, const SensorMapping&)>& mapNudge)
                  {
                     bool success = true;
                     success &= mapButton(ButtonMapping::Create(deviceId, leftTrigger, -0.3f), m_pininput.GetLeftFlipperActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, rightTrigger, -0.3f), m_pininput.GetRightFlipperActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, leftTrigger, 0.3f), m_pininput.GetStagedLeftFlipperActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, rightTrigger, 0.3f), m_pininput.GetStagedRightFlipperActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, leftShoulder), m_pininput.GetLeftMagnaActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, rightShoulder), m_pininput.GetRightMagnaActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, northButton), m_pininput.GetAddCreditActionId(0));
                     success &= mapButton(ButtonMapping::Create(deviceId, eastButton), m_pininput.GetStartActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, southButton), m_pininput.GetLaunchBallActionId());
                     success &= mapButton(ButtonMapping::Create(deviceId, backButton), m_pininput.GetOpenInGameUIActionId());
                     // success &= mapButton(ButtonMapping::Create(deviceId, startButton), m_pininput.()); // In Game UI
                     if (dpadLeftButton != 0xFFFF && dpadRightButton != 0xFFFF && dpadUpButton != 0xFFFF && dpadDownButton != 0xFFFF)
                     {
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadLeftButton), m_pininput.GetServiceActionId(0));
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadDownButton), m_pininput.GetServiceActionId(1));
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadUpButton), m_pininput.GetServiceActionId(2));
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadRightButton), m_pininput.GetServiceActionId(3));

                        success &= mapButton(ButtonMapping::Create(deviceId, dpadUpButton), m_pininput.GetUIUpActionId());
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadDownButton), m_pininput.GetUIDownActionId());
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadLeftButton), m_pininput.GetUILeftActionId());
                        success &= mapButton(ButtonMapping::Create(deviceId, dpadRightButton), m_pininput.GetUIRightActionId());
                     }
                     else
                     {
                        success &= mapButton(ButtonMapping::Create(deviceId, leftStickY, -0.3f), m_pininput.GetUIUpActionId());
                        success &= mapButton(ButtonMapping::Create(deviceId, leftStickY, 0.3f), m_pininput.GetUIDownActionId());
                        success &= mapButton(ButtonMapping::Create(deviceId, leftStickX, -0.3f), m_pininput.GetUILeftActionId());
                        success &= mapButton(ButtonMapping::Create(deviceId, leftStickX, 0.3f), m_pininput.GetUIRightActionId());
                     }
                     success &= mapPlunger(SensorMapping::Create(deviceId, rightStickY, SensorMapping::Type::Position), SensorMapping::Type::Position, true);
                     success &= mapNudge(
                        SensorMapping::Create(deviceId, leftStickX, SensorMapping::Type::Position), SensorMapping::Create(deviceId, leftStickY, SensorMapping::Type::Position));
                     return success;
                  };
                  m_pininput.RegisterDefaultMapping(deviceId, defaultMapping);
               }
               SDL_free(bindings);
            }
            SDL_CloseGamepad(gamepad);
         }
         break;
      }
   }

   void OnJoystickRemoved(SDL_JoystickID id)
   {
      const SDL_Joystick* const joystick = SDL_GetJoystickFromID(id);
      if (joystick == nullptr)
         return;

      auto it = std::ranges::find(m_joysticks, joystick);
      assert(it != m_joysticks.end());
      SDL_CloseJoystick(*it);
      m_joysticks.erase(it);

      uint16_t deviceId = m_joystickIds[id];
      m_pininput.UnregisterDevice(deviceId);
      m_joystickIds.erase(id);
   }

   InputManager& m_pininput;
   vector<SDL_Joystick*> m_joysticks;
   ankerl::unordered_dense::map<SDL_JoystickID, uint16_t> m_joystickIds;
};
